using System;
using System.IO;
using System.Net;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Newtonsoft.Json.Linq;
using WindowsGSM.Functions;

namespace WindowsGSM.GameServer
{
    // Minecraft: Fabric Server — NATIVE (replaces the FabricMC.cs plugin, more reliable).
    // Uses the official Fabric meta API (meta.fabricmc.net) to produce a self-contained
    // server.jar (downloads MC + loader on first launch). MC version pinned at install time.
    class FabricMC
    {
        private readonly ServerConfig _serverData;

        public string Error;
        public string Notice;

        public const string FullName = "Minecraft: Fabric Server";
        public string StartPath = "fabric-server-launch.jar";
        public bool AllowsEmbedConsole = true;
        public int PortIncrements = 1;
        public dynamic QueryMethod = new Query.UT3();

        public string Port = "25565";
        public string QueryPort = "25565";
        public string Defaultmap = "world";
        public string Maxplayers = "20";
        public string Additional = "-Xmx2048M -Xms2048M";

        private const string META = "https://meta.fabricmc.net/v2/versions";
        private string VersionFile => ServerPath.GetServersServerFiles(_serverData.ServerID, "wgsm-fabric-version.txt");

        public FabricMC(ServerConfig serverData)
        {
            _serverData = serverData;
        }

        public async void CreateServerCFG()
        {
            string configPath = ServerPath.GetServersServerFiles(_serverData.ServerID, "server.properties");
            if (await Github.DownloadGameServerConfig(configPath, "Minecraft: Java Edition Server"))
            {
                string c = File.ReadAllText(configPath);
                c = c.Replace("{{serverPort}}", _serverData.ServerPort).Replace("{{maxplayers}}", Maxplayers)
                     .Replace("{{rconPort}}", (int.Parse(_serverData.ServerPort) + 10).ToString())
                     .Replace("{{serverIP}}", _serverData.ServerIP).Replace("{{defaultmap}}", Defaultmap)
                     .Replace("{{rcon_password}}", _serverData.GetRCONPassword()).Replace("{{serverName}}", _serverData.ServerName);
                File.WriteAllText(configPath, c);
            }
        }

        // Gets the latest stable MC version from the Fabric meta API
        private static async Task<string> GetLatestStableGameVersion(WebClient wc)
        {
            string json = await wc.DownloadStringTaskAsync($"{META}/game");
            foreach (var v in JArray.Parse(json))
            {
                if ((bool?)v["stable"] == true) { return v["version"].ToString(); }
            }
            return JArray.Parse(json)[0]["version"].ToString();
        }

        private static async Task<string> GetLatest(WebClient wc, string endpoint, string gameVersion = null)
        {
            string url = gameVersion == null ? $"{META}/{endpoint}" : $"{META}/{endpoint}/{gameVersion}";
            string json = await wc.DownloadStringTaskAsync(url);
            var arr = JArray.Parse(json);
            if (arr.Count == 0) { return null; }
            // /loader/{game} -> [{loader:{version}}], /installer -> [{version}]
            return arr[0]["loader"] != null ? arr[0]["loader"]["version"].ToString() : arr[0]["version"].ToString();
        }

        private async Task<bool> DownloadServerJar(string mcVersion)
        {
            using (WebClient wc = new TimeoutWebClient())
            {
                string loader = await GetLatest(wc, "loader", mcVersion);
                string installer = await GetLatest(wc, "installer");
                if (string.IsNullOrEmpty(loader) || string.IsNullOrEmpty(installer))
                {
                    Error = "Unable to retrieve loader/installer versions from the Fabric API.";
                    return false;
                }
                string jarUrl = $"{META}/loader/{mcVersion}/{loader}/{installer}/server/jar";
                string jarPath = ServerPath.GetServersServerFiles(_serverData.ServerID, StartPath);
                await wc.DownloadFileTaskAsync(jarUrl, jarPath);
                File.WriteAllText(VersionFile, mcVersion); // version pinning
                return true;
            }
        }

        private void WriteEula()
        {
            string eulaPath = ServerPath.GetServersServerFiles(_serverData.ServerID, "eula.txt");
            File.WriteAllText(eulaPath,
                "#Generated by WindowsGSM (agreement to the Minecraft EULA https://aka.ms/MinecraftEULA)\r\neula=true\r\n");
        }

        public async Task<Process> Install()
        {
            // EULA
            if (MessageBox.Show("By continuing, you accept the Minecraft EULA (https://aka.ms/MinecraftEULA).", "EULA", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes)
            { Error = "EULA declined"; return null; }

            // Java
            if (!JavaHelper.IsJREInstalled())
            {
                if (MessageBox.Show("Java is not installed. Install it?", "Java", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes)
                { Error = "Java not installed"; return null; }
                var jre = await JavaHelper.DownloadJREToServer(_serverData.ServerID);
                if (!jre.installed) { Error = jre.error; return null; }
            }

            try
            {
                string mcVersion;
                using (WebClient wc = new TimeoutWebClient()) { mcVersion = await GetLatestStableGameVersion(wc); }
                // Version choice + pinning (empty = latest stable)
                string chosen = PromptVersion("Minecraft version for Fabric", mcVersion);
                if (chosen == null) { Error = "Installation cancelled"; return null; }
                if (!string.IsNullOrWhiteSpace(chosen)) { mcVersion = chosen.Trim(); }

                if (!await DownloadServerJar(mcVersion)) { return null; }
                WriteEula();
                Notice = $"Fabric installed for Minecraft {mcVersion} (pinned version).";
            }
            catch (Exception e) { Error = $"Fabric install failed: {e.Message}"; return null; }

            return null;
        }

        public async Task<Process> Update()
        {
            if (!JavaHelper.IsJREInstalled())
            {
                var jre = await JavaHelper.DownloadJREToServer(_serverData.ServerID);
                if (!jre.installed) { Error = jre.error; return null; }
            }
            try
            {
                // keep the pinned version if present, otherwise latest stable
                string mcVersion = File.Exists(VersionFile) ? File.ReadAllText(VersionFile).Trim() : null;
                if (string.IsNullOrWhiteSpace(mcVersion))
                {
                    using (WebClient wc = new TimeoutWebClient()) { mcVersion = await GetLatestStableGameVersion(wc); }
                }
                string jarPath = ServerPath.GetServersServerFiles(_serverData.ServerID, StartPath);
                if (File.Exists(jarPath)) { File.Delete(jarPath); }
                if (!await DownloadServerJar(mcVersion)) { return null; }
                WriteEula();
                Notice = $"Fabric updated (Minecraft {mcVersion}).";
            }
            catch (Exception e) { Error = $"Fabric update failed: {e.Message}"; return null; }
            return null;
        }

        public async Task<Process> Start()
        {
            string javaPath = JavaHelper.FindJavaExecutableAbsolutePath();
            if (javaPath.Length == 0) { Error = "Java is not installed"; return null; }

            string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
            string jarPath = Path.Combine(workingDir, StartPath);
            if (!File.Exists(jarPath)) { Error = $"{StartPath} not found. Run the installation."; return null; }

            // Checks that the installed Java version is suitable for the pinned MC version.
            string mcPinned = File.Exists(VersionFile) ? File.ReadAllText(VersionFile).Trim() : string.Empty;
            int needed = JavaHelper.RequiredJavaForMinecraft(mcPinned);
            int have = JavaHelper.GetNewestJavaMajorVersion();
            if (needed > 0 && have > 0 && have < needed)
            {
                Error = $"Java {needed}+ required for Minecraft {mcPinned} (Java {have} detected). Install Temurin {needed}: https://adoptium.net/";
                return null;
            }

            WindowsFirewall firewall = new WindowsFirewall("java.exe", javaPath);
            if (!await firewall.IsRuleExist()) { await firewall.AddRule(); }

            Process p = new Process
            {
                StartInfo =
                {
                    WorkingDirectory = workingDir,
                    FileName = javaPath,
                    Arguments = $"{_serverData.ServerParam} -jar {StartPath} nogui",
                    WindowStyle = ProcessWindowStyle.Minimized,
                    CreateNoWindow = AllowsEmbedConsole,
                    UseShellExecute = false,
                    RedirectStandardInput = AllowsEmbedConsole,
                    RedirectStandardOutput = AllowsEmbedConsole,
                    RedirectStandardError = AllowsEmbedConsole
                },
                EnableRaisingEvents = true
            };

            if (AllowsEmbedConsole)
            {
                var console = new ServerConsole(_serverData.ServerID);
                p.OutputDataReceived += console.AddOutput;
                p.ErrorDataReceived += console.AddOutput;
                p.Start();
                p.BeginOutputReadLine();
                p.BeginErrorReadLine();
            }
            else { p.Start(); }

            return p;
        }

        public async Task Stop(Process p)
        {
            await Task.Run(() =>
            {
                if (p.StartInfo.RedirectStandardInput) { p.StandardInput.WriteLine("stop"); }
                else { ServerConsole.SendMessageToMainWindow(p.MainWindowHandle, "stop"); }
            });
        }

        public bool IsInstallValid() => File.Exists(ServerPath.GetServersServerFiles(_serverData.ServerID, StartPath));

        public bool IsImportValid(string path)
        {
            Error = $"Invalid Path! Fail to find {StartPath}";
            return File.Exists(Path.Combine(path, StartPath));
        }

        public string GetLocalBuild()
        {
            // pinned version stored at install time
            if (File.Exists(VersionFile)) { return File.ReadAllText(VersionFile).Trim(); }
            Error = "Unknown local version (reinstall).";
            return string.Empty;
        }

        public async Task<string> GetRemoteBuild()
        {
            try { using (WebClient wc = new TimeoutWebClient()) { return await GetLatestStableGameVersion(wc); } }
            catch { Error = "Fail to get remote build"; return string.Empty; }
        }

        // Mini version-input dialog (returns null if cancelled, "" if default accepted)
        private static string PromptVersion(string title, string defaultValue)
        {
            string result = null;
            var dispatcher = System.Windows.Application.Current?.Dispatcher;
            Action show = () =>
            {
                var win = new Window
                {
                    Title = title, Width = 380, Height = 150, WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = ResizeMode.NoResize, WindowStyle = WindowStyle.ToolWindow
                };
                var grid = new Grid { Margin = new Thickness(12) };
                grid.RowDefinitions.Add(new RowDefinition());
                grid.RowDefinitions.Add(new RowDefinition());
                grid.RowDefinitions.Add(new RowDefinition());
                var lbl = new TextBlock { Text = $"Minecraft version (empty = {defaultValue}):", Margin = new Thickness(0, 0, 0, 6) };
                var tb = new TextBox { Text = string.Empty };
                var ok = new Button { Content = "OK", Width = 90, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) };
                Grid.SetRow(lbl, 0); Grid.SetRow(tb, 1); Grid.SetRow(ok, 2);
                grid.Children.Add(lbl); grid.Children.Add(tb); grid.Children.Add(ok);
                win.Content = grid;
                ok.Click += (s, e) => { result = tb.Text; win.DialogResult = true; };
                win.ShowDialog();
            };
            if (dispatcher != null && !dispatcher.CheckAccess()) { dispatcher.Invoke(show); } else { show(); }
            return result; // null if closed without OK
        }
    }
}
