using System;
using System.IO;
using System.Net;
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Newtonsoft.Json.Linq;
using WindowsGSM.Functions;

namespace WindowsGSM.GameServer
{
    // Minecraft: Forge Server — NATIF (remplace le plugin, plus fiable).
    // Installe via l'installeur officiel Forge (--installServer), résout la version Forge depuis
    // promotions_slim.json, et gère les 2 modes de lancement : moderne (@win_args.txt, MC 1.17+)
    // et ancien (forge-*.jar). Version MC + build Forge épinglés à l'install.
    class ForgeMC
    {
        private readonly ServerConfig _serverData;

        public string Error;
        public string Notice;

        public const string FullName = "Minecraft: Forge Server";
        public string StartPath = "run.bat";
        public bool AllowsEmbedConsole = true;
        public int PortIncrements = 1;
        public dynamic QueryMethod = new Query.UT3();

        public string Port = "25565";
        public string QueryPort = "25565";
        public string Defaultmap = "world";
        public string Maxplayers = "20";
        public string Additional = "-Xmx3072M -Xms3072M";

        private const string PROMOS = "https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json";
        private const string MAVEN = "https://maven.minecraftforge.net/net/minecraftforge/forge";
        private string VersionFile => ServerPath.GetServersServerFiles(_serverData.ServerID, "wgsm-forge-version.txt"); // "mc forge"

        public ForgeMC(ServerConfig serverData)
        {
            _serverData = serverData;
        }

        public async void CreateServerCFG()
        {
            string configPath = ServerPath.GetServersServerFiles(_serverData.ServerID, "server.properties");
            if (await Github.DownloadGameServerConfig(configPath, "Minecraft: Java Edition Server"))
            {
                string c = File.ReadAllText(configPath);
                c = c.Replace("{{serverPort}}", _serverData.ServerPort).Replace("{{maxplayers}}", Maxplayers)
                     .Replace("{{rconPort}}", (int.Parse(_serverData.ServerPort) + 10).ToString())
                     .Replace("{{serverIP}}", _serverData.ServerIP).Replace("{{defaultmap}}", Defaultmap)
                     .Replace("{{rcon_password}}", _serverData.GetRCONPassword()).Replace("{{serverName}}", _serverData.ServerName);
                File.WriteAllText(configPath, c);
            }
        }

        // Résout la version Forge (recommended sinon latest) pour une version MC donnée.
        private async Task<string> ResolveForgeBuild(WebClient wc, string mcVersion)
        {
            string json = await wc.DownloadStringTaskAsync(PROMOS);
            var promos = JObject.Parse(json)["promos"] as JObject;
            if (promos == null) { return null; }
            return promos[$"{mcVersion}-recommended"]?.ToString() ?? promos[$"{mcVersion}-latest"]?.ToString();
        }

        // Dernière version MC ayant une build Forge recommandée (best-effort pour le défaut)
        private async Task<string> GuessLatestMcVersion(WebClient wc)
        {
            try
            {
                string json = await wc.DownloadStringTaskAsync(PROMOS);
                var promos = JObject.Parse(json)["promos"] as JObject;
                var versions = promos.Properties()
                    .Select(p => p.Name.Replace("-recommended", "").Replace("-latest", ""))
                    .Distinct()
                    .Select(v => { var ok = Version.TryParse(v, out var ver); return new { v, ver, ok }; })
                    .Where(x => x.ok)
                    .OrderByDescending(x => x.ver)
                    .ToList();
                return versions.Count > 0 ? versions[0].v : "1.20.1";
            }
            catch { return "1.20.1"; }
        }

        private void WriteEula()
        {
            File.WriteAllText(ServerPath.GetServersServerFiles(_serverData.ServerID, "eula.txt"),
                "#Generated by WindowsGSM (agreement to the Minecraft EULA https://aka.ms/MinecraftEULA)\r\neula=true\r\n");
        }

        // Lance l'installeur Forge (--installServer) et attend la fin.
        private async Task<bool> RunInstaller(string javaPath, string workingDir, string installerName)
        {
            var p = new Process
            {
                StartInfo =
                {
                    WorkingDirectory = workingDir, FileName = javaPath,
                    Arguments = $"-jar {installerName} --installServer",
                    CreateNoWindow = true, UseShellExecute = false,
                    RedirectStandardOutput = true, RedirectStandardError = true
                }
            };
            var console = new ServerConsole(_serverData.ServerID);
            p.OutputDataReceived += console.AddOutput;
            p.ErrorDataReceived += console.AddOutput;
            p.Start();
            p.BeginOutputReadLine();
            p.BeginErrorReadLine();
            await Task.Run(() => p.WaitForExit());
            return p.ExitCode == 0;
        }

        public async Task<Process> Install()
        {
            if (MessageBox.Show("En continuant, tu acceptes l'EULA Minecraft (https://aka.ms/MinecraftEULA).", "EULA", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes)
            { Error = "EULA refusée"; return null; }

            if (!JavaHelper.IsJREInstalled())
            {
                if (MessageBox.Show("Java n'est pas installé. L'installer ?", "Java", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes)
                { Error = "Java non installé"; return null; }
                var jre = await JavaHelper.DownloadJREToServer(_serverData.ServerID);
                if (!jre.installed) { Error = jre.error; return null; }
            }

            try
            {
                string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
                string javaPath = JavaHelper.FindJavaExecutableAbsolutePath();
                if (javaPath.Length == 0) { Error = "Java introuvable après installation"; return null; }

                string mcVersion, forgeBuild;
                using (WebClient wc = new TimeoutWebClient())
                {
                    string defMc = await GuessLatestMcVersion(wc);
                    string chosen = PromptVersion("Version Minecraft pour Forge", defMc);
                    if (chosen == null) { Error = "Installation annulée"; return null; }
                    mcVersion = string.IsNullOrWhiteSpace(chosen) ? defMc : chosen.Trim();

                    forgeBuild = await ResolveForgeBuild(wc, mcVersion);
                    if (string.IsNullOrEmpty(forgeBuild)) { Error = $"Aucune build Forge trouvée pour Minecraft {mcVersion}."; return null; }

                    string installerName = $"forge-{mcVersion}-{forgeBuild}-installer.jar";
                    string installerUrl = $"{MAVEN}/{mcVersion}-{forgeBuild}/{installerName}";
                    await wc.DownloadFileTaskAsync(installerUrl, Path.Combine(workingDir, installerName));

                    WriteEula(); // avant l'install pour les versions qui vérifient

                    if (!await RunInstaller(javaPath, workingDir, installerName))
                    { Error = "L'installeur Forge a échoué (voir la console)."; return null; }

                    File.WriteAllText(VersionFile, $"{mcVersion} {forgeBuild}");
                    try { File.Delete(Path.Combine(workingDir, installerName)); } catch { }
                    Notice = $"Forge {forgeBuild} installé pour Minecraft {mcVersion} (version épinglée).";
                }
            }
            catch (Exception e) { Error = $"Échec install Forge : {e.Message}"; return null; }

            return null;
        }

        public async Task<Process> Update()
        {
            if (!JavaHelper.IsJREInstalled())
            {
                var jre = await JavaHelper.DownloadJREToServer(_serverData.ServerID);
                if (!jre.installed) { Error = jre.error; return null; }
            }
            try
            {
                string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
                string javaPath = JavaHelper.FindJavaExecutableAbsolutePath();
                // garde la version MC épinglée, ré-installe la build Forge recommandée pour cette version
                string mcVersion = File.Exists(VersionFile) ? File.ReadAllText(VersionFile).Split(' ')[0].Trim() : null;
                if (string.IsNullOrWhiteSpace(mcVersion)) { Error = "Version épinglée introuvable (réinstaller)."; return null; }

                using (WebClient wc = new TimeoutWebClient())
                {
                    string forgeBuild = await ResolveForgeBuild(wc, mcVersion);
                    if (string.IsNullOrEmpty(forgeBuild)) { Error = $"Aucune build Forge pour {mcVersion}."; return null; }
                    string installerName = $"forge-{mcVersion}-{forgeBuild}-installer.jar";
                    await wc.DownloadFileTaskAsync($"{MAVEN}/{mcVersion}-{forgeBuild}/{installerName}", Path.Combine(workingDir, installerName));
                    WriteEula();
                    if (!await RunInstaller(javaPath, workingDir, installerName)) { Error = "Installeur Forge échoué."; return null; }
                    File.WriteAllText(VersionFile, $"{mcVersion} {forgeBuild}");
                    try { File.Delete(Path.Combine(workingDir, installerName)); } catch { }
                    Notice = $"Forge mis à jour ({mcVersion} / build {forgeBuild}).";
                }
            }
            catch (Exception e) { Error = $"Échec MAJ Forge : {e.Message}"; return null; }
            return null;
        }

        // Détermine les arguments de lancement selon le mode (moderne @win_args.txt vs ancien forge-*.jar)
        private string ResolveStartArguments(string workingDir)
        {
            string mc = string.Empty, forge = string.Empty;
            if (File.Exists(VersionFile))
            {
                var parts = File.ReadAllText(VersionFile).Trim().Split(' ');
                if (parts.Length >= 2) { mc = parts[0]; forge = parts[1]; }
            }

            // Moderne (MC 1.17+) : libraries/net/minecraftforge/forge/<mc>-<forge>/win_args.txt
            string winArgs = Path.Combine("libraries", "net", "minecraftforge", "forge", $"{mc}-{forge}", "win_args.txt");
            if (!string.IsNullOrEmpty(mc) && File.Exists(Path.Combine(workingDir, winArgs)))
            {
                string jvm = File.Exists(Path.Combine(workingDir, "user_jvm_args.txt")) ? "@user_jvm_args.txt " : string.Empty;
                return $"{_serverData.ServerParam} {jvm}@{winArgs} nogui";
            }

            // Ancien : forge-<mc>-<forge>.jar (ou un *.jar Forge non-installeur)
            string oldJar = $"forge-{mc}-{forge}.jar";
            if (!string.IsNullOrEmpty(mc) && File.Exists(Path.Combine(workingDir, oldJar)))
            {
                return $"{_serverData.ServerParam} -jar {oldJar} nogui";
            }
            var anyForge = Directory.Exists(workingDir)
                ? Directory.GetFiles(workingDir, "forge-*.jar").FirstOrDefault(f => !f.Contains("installer"))
                : null;
            if (anyForge != null)
            {
                return $"{_serverData.ServerParam} -jar {Path.GetFileName(anyForge)} nogui";
            }
            return null;
        }

        public async Task<Process> Start()
        {
            string javaPath = JavaHelper.FindJavaExecutableAbsolutePath();
            if (javaPath.Length == 0) { Error = "Java n'est pas installé"; return null; }

            string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
            string args = ResolveStartArguments(workingDir);
            if (args == null) { Error = "Forge non installé (ni win_args.txt ni forge-*.jar). Lance l'installation."; return null; }

            // Vérifie que la version de Java installée convient à la version MC épinglée.
            string mcPinned = File.Exists(VersionFile) ? File.ReadAllText(VersionFile).Trim().Split(' ')[0] : string.Empty;
            int needed = JavaHelper.RequiredJavaForMinecraft(mcPinned);
            int have = JavaHelper.GetNewestJavaMajorVersion();
            if (needed > 0 && have > 0 && have < needed)
            {
                Error = $"Java {needed}+ requis pour Minecraft {mcPinned} (Java {have} détecté). Installe Temurin {needed} : https://adoptium.net/";
                return null;
            }

            WindowsFirewall firewall = new WindowsFirewall("java.exe", javaPath);
            if (!await firewall.IsRuleExist()) { await firewall.AddRule(); }

            Process p = new Process
            {
                StartInfo =
                {
                    WorkingDirectory = workingDir, FileName = javaPath, Arguments = args,
                    WindowStyle = ProcessWindowStyle.Minimized,
                    CreateNoWindow = AllowsEmbedConsole, UseShellExecute = false,
                    RedirectStandardInput = AllowsEmbedConsole,
                    RedirectStandardOutput = AllowsEmbedConsole,
                    RedirectStandardError = AllowsEmbedConsole
                },
                EnableRaisingEvents = true
            };

            if (AllowsEmbedConsole)
            {
                var console = new ServerConsole(_serverData.ServerID);
                p.OutputDataReceived += console.AddOutput;
                p.ErrorDataReceived += console.AddOutput;
                p.Start(); p.BeginOutputReadLine(); p.BeginErrorReadLine();
            }
            else { p.Start(); }

            return p;
        }

        public async Task Stop(Process p)
        {
            await Task.Run(() =>
            {
                if (p.StartInfo.RedirectStandardInput) { p.StandardInput.WriteLine("stop"); }
                else { ServerConsole.SendMessageToMainWindow(p.MainWindowHandle, "stop"); }
            });
        }

        public bool IsInstallValid()
        {
            string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
            return ResolveStartArguments(workingDir) != null;
        }

        public bool IsImportValid(string path)
        {
            Error = "Invalid Path! Fail to find run.bat or forge-*.jar";
            return File.Exists(Path.Combine(path, "run.bat")) || (Directory.Exists(path) && Directory.GetFiles(path, "forge-*.jar").Any(f => !f.Contains("installer")));
        }

        public string GetLocalBuild()
        {
            if (File.Exists(VersionFile)) { return File.ReadAllText(VersionFile).Trim().Split(' ')[0]; }
            Error = "Version locale inconnue (réinstaller).";
            return string.Empty;
        }

        public async Task<string> GetRemoteBuild()
        {
            // build Forge recommandée pour la version MC épinglée
            string mc = File.Exists(VersionFile) ? File.ReadAllText(VersionFile).Trim().Split(' ')[0] : null;
            if (string.IsNullOrEmpty(mc)) { Error = "Version épinglée inconnue"; return string.Empty; }
            try { using (WebClient wc = new TimeoutWebClient()) { return await ResolveForgeBuild(wc, mc) ?? string.Empty; } }
            catch { Error = "Fail to get remote build"; return string.Empty; }
        }

        private static string PromptVersion(string title, string defaultValue)
        {
            string result = null;
            var dispatcher = System.Windows.Application.Current?.Dispatcher;
            Action show = () =>
            {
                var win = new Window { Title = title, Width = 380, Height = 150, WindowStartupLocation = WindowStartupLocation.CenterScreen, ResizeMode = ResizeMode.NoResize, WindowStyle = WindowStyle.ToolWindow };
                var grid = new Grid { Margin = new Thickness(12) };
                grid.RowDefinitions.Add(new RowDefinition()); grid.RowDefinitions.Add(new RowDefinition()); grid.RowDefinitions.Add(new RowDefinition());
                var lbl = new TextBlock { Text = $"Version Minecraft (vide = {defaultValue}) :", Margin = new Thickness(0, 0, 0, 6) };
                var tb = new TextBox { Text = string.Empty };
                var ok = new Button { Content = "OK", Width = 90, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 10, 0, 0) };
                Grid.SetRow(lbl, 0); Grid.SetRow(tb, 1); Grid.SetRow(ok, 2);
                grid.Children.Add(lbl); grid.Children.Add(tb); grid.Children.Add(ok);
                win.Content = grid;
                ok.Click += (s, e) => { result = tb.Text; win.DialogResult = true; };
                win.ShowDialog();
            };
            if (dispatcher != null && !dispatcher.CheckAccess()) { dispatcher.Invoke(show); } else { show(); }
            return result;
        }
    }
}
