using System.Collections.Generic;

namespace WindowsGSM.Functions.Localization
{
    /// <summary>
    /// Translation tables for the fork UI. Add entries with E(key, en, fr, es, de).
    /// Keys are namespaced by module (e.g. "WebUsers.Title"). English is the source/fallback.
    /// </summary>
    internal static class LocStrings
    {
        public static readonly Dictionary<string, Dictionary<string, string>> All = Build();

        private static Dictionary<string, Dictionary<string, string>> Build()
        {
            var all = new Dictionary<string, Dictionary<string, string>>();
            foreach (var l in Loc.Supported) { all[l] = new Dictionary<string, string>(); }

            void E(string key, string en, string fr, string es, string de)
            {
                all["en"][key] = en; all["fr"][key] = fr; all["es"][key] = es; all["de"][key] = de;
            }

            // ==== Common ====
            E("Common.Close", "Close", "Fermer", "Cerrar", "Schließen");
            E("Common.Save", "Save", "Enregistrer", "Guardar", "Speichern");
            E("Common.Cancel", "Cancel", "Annuler", "Cancelar", "Abbrechen");
            E("Common.Remove", "Remove", "Supprimer", "Eliminar", "Entfernen");
            E("Common.Generate", "Generate", "Générer", "Generar", "Generieren");

            // ==== Server status (grid display only; Status stays English for logic) ====
            E("Status.Started", "Started", "Démarré", "Iniciado", "Gestartet");
            E("Status.Stopped", "Stopped", "Arrêté", "Detenido", "Gestoppt");
            E("Status.Starting", "Starting", "Démarrage…", "Iniciando…", "Startet…");
            E("Status.Stopping", "Stopping", "Arrêt…", "Deteniendo…", "Stoppt…");
            E("Status.Restarting", "Restarting", "Redémarrage…", "Reiniciando…", "Neustart…");
            E("Status.Restarted", "Restarted", "Redémarré", "Reiniciado", "Neu gestartet");
            E("Status.Updating", "Updating", "Mise à jour…", "Actualizando…", "Aktualisiert…");
            E("Status.Updated", "Updated", "Mis à jour", "Actualizado", "Aktualisiert");
            E("Status.Backuping", "Backuping", "Sauvegarde…", "Copia de seguridad…", "Sicherung…");
            E("Status.Backuped", "Backuped", "Sauvegardé", "Copiado", "Gesichert");
            E("Status.Restoring", "Restoring", "Restauration…", "Restaurando…", "Wiederherstellung…");
            E("Status.Restored", "Restored", "Restauré", "Restaurado", "Wiederhergestellt");
            E("Status.Deleting", "Deleting", "Suppression…", "Eliminando…", "Löscht…");

            // ==== Web portal accounts (WebUsersDialog) ====
            E("WebUsers.Title", "Web portal accounts", "Comptes du portail web", "Cuentas del portal web", "Web-Portal-Konten");
            E("WebUsers.RolesHelp",
                "Roles: Viewer (read) · Operator (+ start/stop/restart/backup) · Admin (all). Tick the servers each account may access.",
                "Rôles : Viewer (lecture) · Operator (+ start/stop/restart/backup) · Admin (tout). Cochez les serveurs autorisés pour chaque compte.",
                "Roles: Viewer (lectura) · Operator (+ start/stop/restart/backup) · Admin (todo). Marque los servidores permitidos para cada cuenta.",
                "Rollen: Viewer (Lesen) · Operator (+ Start/Stopp/Neustart/Backup) · Admin (alles). Wählen Sie die für jedes Konto erlaubten Server.");
            E("WebUsers.Username", "Username", "Utilisateur", "Usuario", "Benutzername");
            E("WebUsers.Password", "Password", "Mot de passe", "Contraseña", "Passwort");
            E("WebUsers.Role", "Role", "Rôle", "Rol", "Rolle");
            E("WebUsers.AllowedServers", "Allowed servers", "Serveurs autorisés", "Servidores permitidos", "Erlaubte Server");
            E("WebUsers.AllServers", "All servers", "Tous les serveurs", "Todos los servidores", "Alle Server");
            E("WebUsers.NoServers", "(no servers found)", "(aucun serveur trouvé)", "(no se encontraron servidores)", "(keine Server gefunden)");
            E("WebUsers.AddUpdate", "Add / Update", "Ajouter / Mettre à jour", "Añadir / Actualizar", "Hinzufügen / Aktualisieren");
            E("WebUsers.Removed", "Account removed.", "Compte supprimé.", "Cuenta eliminada.", "Konto entfernt.");
            E("WebUsers.UserRequired", "Username required.", "Nom d'utilisateur requis.", "Se requiere un nombre de usuario.", "Benutzername erforderlich.");
            E("WebUsers.PwRequired", "Password required for a new account.", "Mot de passe requis pour un nouveau compte.", "Se requiere una contraseña para una cuenta nueva.", "Passwort für ein neues Konto erforderlich.");
            E("WebUsers.PickServer",
                "Tick at least one server, or choose \"All servers\".",
                "Cochez au moins un serveur, ou choisissez « Tous les serveurs ».",
                "Marque al menos un servidor o elija «Todos los servidores».",
                "Wählen Sie mindestens einen Server oder „Alle Server“.");
            E("WebUsers.Saved", "Account \"{0}\" saved ({1}).", "Compte « {0} » enregistré ({1}).", "Cuenta «{0}» guardada ({1}).", "Konto „{0}“ gespeichert ({1}).");
            E("WebUsers.ScopeAll", "all servers", "tous les serveurs", "todos los servidores", "alle Server");
            E("WebUsers.ScopeServers", "servers {0}", "serveurs {0}", "servidores {0}", "Server {0}");

            // ==== ApiToken ====
            E("ApiToken.Title", "API Token — #{0} {1}", "Jeton API — #{0} {1}", "Token de API — #{0} {1}", "API-Token — #{0} {1}");
            E("ApiToken.HelpSatisfactory", "Satisfactory: enter the server PASSWORD (Client or Admin) — WGSM obtains a token by itself\nvia the API to read the player count (read-only). An API token (server.GenerateAPIToken) also works.", "Satisfactory : saisis le MOT DE PASSE du serveur (Client ou Admin) — WGSM obtient un token par lui-même\nvia l'API pour lire le nombre de joueurs (lecture seule). Un token API (server.GenerateAPIToken) fonctionne aussi.", "Satisfactory: introduce la CONTRASEÑA del servidor (Cliente o Admin) — WGSM obtiene un token por sí mismo\na través de la API para leer el número de jugadores (solo lectura). Un token de API (server.GenerateAPIToken) también funciona.", "Satisfactory: Gib das SERVER-PASSWORT ein (Client oder Admin) — WGSM ermittelt selbst ein Token\nüber die API, um die Spieleranzahl zu lesen (schreibgeschützt). Ein API-Token (server.GenerateAPIToken) funktioniert ebenfalls.");
            E("ApiToken.HelpGeneric", "API token used to query this server. Paste it below.", "Token API utilisé pour interroger ce serveur. Colle-le ci-dessous.", "Token de API usado para consultar este servidor. Pégalo abajo.", "API-Token zur Abfrage dieses Servers. Füge es unten ein.");
            E("ApiToken.FieldLabel", "API Token", "Jeton API", "Token de API", "API-Token");
            E("ApiToken.Save", "Save", "Enregistrer", "Guardar", "Speichern");
            E("ApiToken.Clear", "Clear", "Effacer", "Borrar", "Leeren");
            E("ApiToken.Close", "Close", "Fermer", "Cerrar", "Schließen");

            // ==== Config ====
            E("Config.Title", "Configuration — #{0} {1}", "Configuration — #{0} {1}", "Configuración — #{0} {1}", "Konfiguration — #{0} {1}");
            E("Config.FileLabel", "File:", "Fichier :", "Archivo:", "Datei:");
            E("Config.GameSettings", "{0} settings", "Paramètres {0}", "Ajustes de {0}", "{0}-Einstellungen");
            E("Config.NoFile", "No configuration file found in serverfiles.\n(The server may not be installed yet.)", "Aucun fichier de configuration trouvé dans serverfiles.\n(Le serveur n'est peut-être pas encore installé.)", "No se encontró ningún archivo de configuración en serverfiles.\n(Puede que el servidor aún no esté instalado.)", "Keine Konfigurationsdatei in serverfiles gefunden.\n(Der Server ist möglicherweise noch nicht installiert.)");
            E("Config.CannotRead", "Cannot read: {0}", "Lecture impossible : {0}", "No se puede leer: {0}", "Kann nicht gelesen werden: {0}");
            E("Config.OtherSettings", "Other settings ({0}) — raw editing", "Autres paramètres ({0}) — édition brute", "Otros ajustes ({0}) — edición sin formato", "Weitere Einstellungen ({0}) — Rohbearbeitung");
            E("Config.NoEntries", "No recognized key/value entry in this file.", "Aucune entrée clé/valeur reconnue dans ce fichier.", "No hay ninguna entrada clave/valor reconocida en este archivo.", "Kein erkannter Schlüssel/Wert-Eintrag in dieser Datei.");
            E("Config.GlobalSection", "(global)", "(global)", "(global)", "(global)");
            E("Config.Saved", "✔ Saved (.wgsmbak backup created). Restart the server to apply.", "✔ Enregistré (sauvegarde .wgsmbak créée). Redémarre le serveur pour appliquer.", "✔ Guardado (copia de seguridad .wgsmbak creada). Reinicia el servidor para aplicar.", "✔ Gespeichert (.wgsmbak-Sicherung erstellt). Starte den Server neu, um zu übernehmen.");
            E("Config.SaveFailed", "Failed: {0}", "Échec : {0}", "Error: {0}", "Fehlgeschlagen: {0}");

            // ==== Doctor ====
            E("Doctor.Title", "Server Doctor", "Docteur du serveur", "Doctor del servidor", "Server-Doktor");
            E("Doctor.ServerLabel", "Server:", "Serveur :", "Servidor:", "Server:");
            E("Doctor.ExternalButton", "External reachability…", "Accessibilité externe…", "Accesibilidad externa…", "Externe Erreichbarkeit…");
            E("Doctor.Retest", "Re-test", "Retester", "Repetir prueba", "Erneut testen");
            E("Doctor.NoServer", "No server to diagnose.", "Aucun serveur à diagnostiquer.", "Ningún servidor que diagnosticar.", "Kein Server zum Diagnostizieren.");
            E("Doctor.ExternalHeader", "External reachability (via check-host.net)", "Accessibilité externe (via check-host.net)", "Accesibilidad externa (vía check-host.net)", "Externe Erreichbarkeit (über check-host.net)");
            E("Doctor.ExternalInProgress", "⏳ Test in progress… (your public IP is sent to check-host.net)", "⏳ Test en cours… (ton IP publique est envoyée à check-host.net)", "⏳ Prueba en curso… (tu IP pública se envía a check-host.net)", "⏳ Test läuft… (deine öffentliche IP wird an check-host.net gesendet)");
            E("Doctor.Error", "Error: {0}", "Erreur : {0}", "Error: {0}", "Fehler: {0}");
            E("Doctor.CheckServerStatus", "Server status", "État du serveur", "Estado del servidor", "Serverstatus");
            E("Doctor.StatusRunning", "Running.", "En cours d'exécution.", "En ejecución.", "Läuft.");
            E("Doctor.StatusStopped", "Stopped (listening-port checks are skipped).", "Arrêté (les vérifications de ports en écoute sont ignorées).", "Detenido (se omiten las comprobaciones de puertos en escucha).", "Gestoppt (Prüfungen der lauschenden Ports werden übersprungen).");
            E("Doctor.CheckInternet", "Internet reachability", "Accessibilité Internet", "Accesibilidad de Internet", "Internet-Erreichbarkeit");
            E("Doctor.InternetDetail", "Depends on the firewall + port-forward on the router (see Tools ▸ Ports / UPnP). This diagnostic checks LOCAL listening, not the opening on the router side.", "Dépend du pare-feu + de la redirection de port sur le routeur (voir Outils ▸ Ports / UPnP). Ce diagnostic vérifie l'écoute LOCALE, pas l'ouverture côté routeur.", "Depende del cortafuegos + la redirección de puertos en el router (ver Herramientas ▸ Puertos / UPnP). Este diagnóstico comprueba la escucha LOCAL, no la apertura en el lado del router.", "Hängt von der Firewall + Portweiterleitung am Router ab (siehe Tools ▸ Ports / UPnP). Diese Diagnose prüft das LOKALE Lauschen, nicht die Öffnung auf der Router-Seite.");
            E("Doctor.CheckPorts", "Ports", "Ports", "Puertos", "Ports");
            E("Doctor.PortsNoneInferred", "No port inferred (incomplete config?).", "Aucun port déduit (configuration incomplète ?).", "No se dedujo ningún puerto (¿configuración incompleta?).", "Kein Port ermittelt (unvollständige Konfiguration?).");
            E("Doctor.PortsListFailed", "Unable to list listening ports: {0}", "Impossible de lister les ports en écoute : {0}", "No se pueden listar los puertos en escucha: {0}", "Lauschende Ports können nicht aufgelistet werden: {0}");
            E("Doctor.PortName", "Port {0} ({1})", "Port {0} ({1})", "Puerto {0} ({1})", "Port {0} ({1})");
            E("Doctor.PortServerStopped", "Server stopped.", "Serveur arrêté.", "Servidor detenido.", "Server gestoppt.");
            E("Doctor.PortListening", "Listening locally.", "En écoute localement.", "En escucha localmente.", "Lauscht lokal.");
            E("Doctor.PortNotListening", "NOT listening while the server is running (wrong port/protocol, or not yet initialized?).", "PAS en écoute alors que le serveur tourne (mauvais port/protocole, ou pas encore initialisé ?).", "NO está en escucha mientras el servidor se ejecuta (¿puerto/protocolo incorrecto, o aún no inicializado?).", "Lauscht NICHT, während der Server läuft (falscher Port/Protokoll oder noch nicht initialisiert?).");
            E("Doctor.CheckDisk", "Disk space", "Espace disque", "Espacio en disco", "Speicherplatz");
            E("Doctor.DiskFree", "{0} GB free on {1}.", "{0} Go libres sur {1}.", "{0} GB libres en {1}.", "{0} GB frei auf {1}.");
            E("Doctor.DiskFreeLow", "{0} GB free on {1} (low).", "{0} Go libres sur {1} (faible).", "{0} GB libres en {1} (bajo).", "{0} GB frei auf {1} (wenig).");
            E("Doctor.PublicIP", "Public IP", "IP publique", "IP pública", "Öffentliche IP");
            E("Doctor.PublicIPFailed", "Unable to obtain it: {0}", "Impossible de l'obtenir : {0}", "No se puede obtener: {0}", "Kann nicht abgerufen werden: {0}");
            E("Doctor.ExternalPortName", "External {0} ({1})", "Externe {0} ({1})", "Externo {0} ({1})", "Extern {0} ({1})");
            E("Doctor.ExternalUdp", "UDP: not reliably verifiable from the outside — test in-game.", "UDP : non vérifiable de manière fiable depuis l'extérieur — teste en jeu.", "UDP: no verificable de forma fiable desde el exterior — pruébalo en el juego.", "UDP: von außen nicht zuverlässig überprüfbar — teste es im Spiel.");
            E("Doctor.CheckHostNoReqId", "check-host.net: no request_id.", "check-host.net : pas de request_id.", "check-host.net: sin request_id.", "check-host.net: keine request_id.");
            E("Doctor.ExtOpen", "Open from the Internet ({0} node(s) were able to connect).", "Ouvert depuis Internet ({0} nœud(s) ont pu se connecter).", "Abierto desde Internet ({0} nodo(s) pudieron conectarse).", "Vom Internet aus offen ({0} Knoten konnten sich verbinden).");
            E("Doctor.ExtNotReachable", "NOT reachable from the outside (connection refused/timeout). Check firewall + port-forward.", "PAS accessible depuis l'extérieur (connexion refusée/expirée). Vérifie le pare-feu + la redirection de port.", "NO accesible desde el exterior (conexión rechazada/tiempo agotado). Comprueba el cortafuegos + la redirección de puertos.", "Von außen NICHT erreichbar (Verbindung abgelehnt/Zeitüberschreitung). Prüfe Firewall + Portweiterleitung.");
            E("Doctor.ExtUndetermined", "Undetermined (no clear response from the probes).", "Indéterminé (aucune réponse claire des sondes).", "Indeterminado (sin respuesta clara de las sondas).", "Unbestimmt (keine eindeutige Antwort von den Sonden).");
            E("Doctor.CheckHostError", "check-host.net: {0}", "check-host.net : {0}", "check-host.net: {0}", "check-host.net: {0}");
            E("Doctor.JavaNone", "No Java detected (required for Minecraft). See adoptium.net.", "Aucun Java détecté (requis pour Minecraft). Voir adoptium.net.", "No se detectó Java (necesario para Minecraft). Ver adoptium.net.", "Kein Java erkannt (für Minecraft erforderlich). Siehe adoptium.net.");
            E("Doctor.JavaDetected", "Java {0} detected. (Recent MC requires 17/21 — adjust if needed.)", "Java {0} détecté. (Les versions récentes de MC requièrent 17/21 — ajuste si besoin.)", "Java {0} detectado. (MC reciente requiere 17/21 — ajústalo si es necesario.)", "Java {0} erkannt. (Aktuelles MC benötigt 17/21 — bei Bedarf anpassen.)");
            E("Doctor.TruckPackagesOk", "server_packages.sii + .dat present (map/DLC OK).", "server_packages.sii + .dat présents (carte/DLC OK).", "server_packages.sii + .dat presentes (mapa/DLC OK).", "server_packages.sii + .dat vorhanden (Karte/DLC OK).");
            E("Doctor.TruckPackagesMissing", "Missing -> the server won't start. In the client (g_console 1), type \"export_server_packages\" with ALL your DLC loaded, then start the server: the plugin copies save\\server_packages.sii + .dat automatically.", "Manquants -> le serveur ne démarrera pas. Dans le client (g_console 1), tape \"export_server_packages\" avec TOUS tes DLC chargés, puis démarre le serveur : le plugin copie save\\server_packages.sii + .dat automatiquement.", "Faltan -> el servidor no arrancará. En el cliente (g_console 1), escribe \"export_server_packages\" con TODOS tus DLC cargados, luego inicia el servidor: el complemento copia save\\server_packages.sii + .dat automáticamente.", "Fehlen -> der Server startet nicht. Gib im Client (g_console 1) \"export_server_packages\" mit ALLEN geladenen DLCs ein, starte dann den Server: das Plugin kopiert save\\server_packages.sii + .dat automatisch.");

            // ==== Donator ====
            E("Donator.Title", "Donor feature", "Fonctionnalité donateur", "Función para donantes", "Spender-Funktion");
            E("Donator.Explain", "Donor-only feature. Become a donor via \"Donor Connect\" in Settings (Patreon), or — if you are the owner — unlock with your passphrase.", "Fonctionnalité réservée aux donateurs. Devenez donateur via « Donor Connect » dans les Paramètres (Patreon) ou, si vous êtes le propriétaire, déverrouillez avec votre phrase secrète.", "Función exclusiva para donantes. Conviértete en donante mediante «Donor Connect» en Ajustes (Patreon) o, si eres el propietario, desbloquéala con tu frase de contraseña.", "Nur für Spender verfügbare Funktion. Werden Sie über „Donor Connect“ in den Einstellungen (Patreon) zum Spender oder – wenn Sie der Eigentümer sind – schalten Sie sie mit Ihrer Passphrase frei.");
            E("Donator.OwnerPassphrase", "Owner passphrase:", "Phrase secrète du propriétaire :", "Frase de contraseña del propietario:", "Passphrase des Eigentümers:");
            E("Donator.Unlock", "Unlock", "Déverrouiller", "Desbloquear", "Freischalten");
            E("Donator.Unlocked", "✔ Unlocked.", "✔ Déverrouillé.", "✔ Desbloqueado.", "✔ Freigeschaltet.");
            E("Donator.BadPassphrase", "Incorrect passphrase (or owner key not yet configured).", "Phrase secrète incorrecte (ou clé propriétaire pas encore configurée).", "Frase de contraseña incorrecta (o clave de propietario aún no configurada).", "Falsche Passphrase (oder Eigentümerschlüssel noch nicht konfiguriert).");

            // ==== GenericSteam ====
            E("GenericSteam.Title", "Add a Steam server (AppID)", "Ajouter un serveur Steam (AppID)", "Añadir un servidor Steam (AppID)", "Steam-Server hinzufügen (AppID)");
            E("GenericSteam.Intro", "Search for a game by name, or directly enter a Steam AppID. WGSM resolves the executable and arguments automatically, installs via SteamCMD, then adds the server.", "Recherche un jeu par son nom, ou saisis directement un AppID Steam. WGSM résout automatiquement l'exécutable et les arguments, installe via SteamCMD, puis ajoute le serveur.", "Busca un juego por su nombre o introduce directamente un AppID de Steam. WGSM resuelve automáticamente el ejecutable y los argumentos, instala mediante SteamCMD y luego añade el servidor.", "Suche ein Spiel nach Namen oder gib direkt eine Steam-AppID ein. WGSM ermittelt automatisch die ausführbare Datei und die Argumente, installiert über SteamCMD und fügt anschließend den Server hinzu.");
            E("GenericSteam.Search", "Search", "Rechercher", "Buscar", "Suchen");
            E("GenericSteam.Install", "Install", "Installer", "Instalar", "Installieren");
            E("GenericSteam.ColGame", "Game", "Jeu", "Juego", "Spiel");
            E("GenericSteam.Searching", "Searching…", "Recherche en cours…", "Buscando…", "Suche läuft…");
            E("GenericSteam.NoResults", "No results (check the name, or enter the AppID directly).", "Aucun résultat (vérifie le nom, ou saisis directement l'AppID).", "Sin resultados (comprueba el nombre o introduce directamente el AppID).", "Keine Ergebnisse (überprüfe den Namen oder gib die AppID direkt ein).");
            E("GenericSteam.ResultCount", "{0} result(s). Select a row, then Install.", "{0} résultat(s). Sélectionne une ligne, puis Installer.", "{0} resultado(s). Selecciona una fila y luego Instalar.", "{0} Ergebnis(se). Wähle eine Zeile aus und klicke dann auf Installieren.");
            E("GenericSteam.SearchError", "Search error: {0}", "Erreur de recherche : {0}", "Error de búsqueda: {0}", "Suchfehler: {0}");
            E("GenericSteam.EnterNumericAppId", "Enter a numeric AppID (or select a game from the list).", "Saisis un AppID numérique (ou sélectionne un jeu dans la liste).", "Introduce un AppID numérico (o selecciona un juego de la lista).", "Gib eine numerische AppID ein (oder wähle ein Spiel aus der Liste).");
            E("GenericSteam.Resolving", "Resolving the executable (AppInfo)…", "Résolution de l'exécutable (AppInfo)…", "Resolviendo el ejecutable (AppInfo)…", "Ausführbare Datei wird ermittelt (AppInfo)…");
            E("GenericSteam.ResolveFailed", "Unable to resolve the Windows executable for AppID {0} (game missing from SteamAppInfo or no Windows launch).", "Impossible de résoudre l'exécutable Windows pour l'AppID {0} (jeu absent de SteamAppInfo ou aucun lancement Windows).", "No se pudo resolver el ejecutable de Windows para el AppID {0} (juego ausente de SteamAppInfo o sin lanzamiento en Windows).", "Die Windows-Programmdatei für AppID {0} konnte nicht ermittelt werden (Spiel fehlt in SteamAppInfo oder kein Windows-Start).");
            E("GenericSteam.ResolveError", "Resolution error: {0}", "Erreur de résolution : {0}", "Error de resolución: {0}", "Auflösungsfehler: {0}");

            // ==== Mods ====
            E("Mods.Title", "Mods — #{0} {1}", "Mods — #{0} {1}", "Mods — #{0} {1}", "Mods — #{0} {1}");
            E("Mods.UnrecognizedGame", "Mods — unrecognized game", "Mods — jeu non reconnu", "Mods — juego no reconocido", "Mods — nicht erkanntes Spiel");
            E("Mods.HeaderFileMods", "File mods — {0}", "Mods fichiers — {0}", "Mods de archivo — {0}", "Datei-Mods — {0}");
            E("Mods.HeaderWorkshop", "Steam Workshop — {0}", "Steam Workshop — {0}", "Steam Workshop — {0}", "Steam Workshop — {0}");
            E("Mods.HeaderGeneric", "Mods — {0}", "Mods — {0}", "Mods — {0}", "Mods — {0}");
            E("Mods.NoProfile", "This game has no known mod profile. You can open the server folder and manage the files manually.", "Ce jeu n'a pas de profil de mods connu. Tu peux ouvrir le dossier du serveur et gérer les fichiers manuellement.", "Este juego no tiene un perfil de mods conocido. Puedes abrir la carpeta del servidor y gestionar los archivos manualmente.", "Für dieses Spiel ist kein Mod-Profil bekannt. Du kannst den Serverordner öffnen und die Dateien manuell verwalten.");
            E("Mods.OpenServerFolder", "Open the server folder", "Ouvrir le dossier du serveur", "Abrir la carpeta del servidor", "Serverordner öffnen");
            E("Mods.NoModSystem", "No server mod system for this game.", "Aucun système de mods serveur pour ce jeu.", "Este juego no tiene sistema de mods de servidor.", "Kein Server-Mod-System für dieses Spiel.");
            E("Mods.AddMod", "Add a mod…", "Ajouter un mod…", "Añadir un mod…", "Mod hinzufügen…");
            E("Mods.OpenFolder", "Open the folder", "Ouvrir le dossier", "Abrir la carpeta", "Ordner öffnen");
            E("Mods.Refresh", "Refresh", "Actualiser", "Actualizar", "Aktualisieren");
            E("Mods.NoModsYet", "No mods yet. Click \"Add a mod…\" or drop files into the folder.", "Aucun mod pour l'instant. Clique sur « Ajouter un mod… » ou dépose des fichiers dans le dossier.", "Todavía no hay mods. Haz clic en «Añadir un mod…» o suelta archivos en la carpeta.", "Noch keine Mods. Klicke auf „Mod hinzufügen…“ oder lege Dateien im Ordner ab.");
            E("Mods.TypeFolder", "folder", "dossier", "carpeta", "Ordner");
            E("Mods.Disabled", "disabled", "désactivé", "desactivado", "deaktiviert");
            E("Mods.EnabledMsg", "\"{0}\" enabled. Restart the server to apply.", "« {0} » activé. Redémarre le serveur pour appliquer.", "«{0}» activado. Reinicia el servidor para aplicar.", "„{0}“ aktiviert. Starte den Server neu, um es anzuwenden.");
            E("Mods.DisabledMsg", "\"{0}\" disabled. Restart the server to apply.", "« {0} » désactivé. Redémarre le serveur pour appliquer.", "«{0}» desactivado. Reinicia el servidor para aplicar.", "„{0}“ deaktiviert. Starte den Server neu, um es anzuwenden.");
            E("Mods.FilterMods", "Mods", "Mods", "Mods", "Mods");
            E("Mods.FilterAllFiles", "All files", "Tous les fichiers", "Todos los archivos", "Alle Dateien");
            E("Mods.ChooseMods", "Choose one or more mods", "Choisir un ou plusieurs mods", "Elegir uno o varios mods", "Einen oder mehrere Mods auswählen");
            E("Mods.ModsAdded", "{0} mod(s) added.", "{0} mod(s) ajouté(s).", "{0} mod(s) añadido(s).", "{0} Mod(s) hinzugefügt.");
            E("Mods.AddLabel", "Add:", "Ajouter :", "Añadir:", "Hinzufügen:");
            E("Mods.WorkshopId", "Workshop ID", "ID Workshop", "ID de Workshop", "Workshop-ID");
            E("Mods.NameOptional", "Name (optional)", "Nom (facultatif)", "Nombre (opcional)", "Name (optional)");
            E("Mods.InvalidWorkshopId", "Invalid Workshop ID (digits only).", "ID Workshop invalide (chiffres uniquement).", "ID de Workshop no válido (solo dígitos).", "Ungültige Workshop-ID (nur Ziffern).");
            E("Mods.DownloadSteamCmd", "Download (SteamCMD)", "Télécharger (SteamCMD)", "Descargar (SteamCMD)", "Herunterladen (SteamCMD)");
            E("Mods.WriteConfigKey", "Write {0} to the config", "Écrire {0} dans la config", "Escribir {0} en la config", "{0} in die Konfiguration schreiben");
            E("Mods.NoWorkshopMods", "No Workshop mods. Paste an ID (the number in the Steam Workshop URL) and click +.", "Aucun mod Workshop. Colle un ID (le numéro dans l'URL du Steam Workshop) et clique sur +.", "No hay mods de Workshop. Pega un ID (el número en la URL del Steam Workshop) y haz clic en +.", "Keine Workshop-Mods. Füge eine ID ein (die Nummer in der Steam-Workshop-URL) und klicke auf +.");
            E("Mods.RemoveFromList", "Remove from the list", "Retirer de la liste", "Quitar de la lista", "Aus der Liste entfernen");
            E("Mods.Downloading", "Downloading {0}…", "Téléchargement de {0}…", "Descargando {0}…", "{0} wird heruntergeladen…");
            E("Mods.DownloadFinished", "Download finished: {0} OK, {1} failure(s). Then \"Write {2}\" if applicable.", "Téléchargement terminé : {0} OK, {1} échec(s). Ensuite « Écrire {2} » si nécessaire.", "Descarga finalizada: {0} OK, {1} fallo(s). Luego «Escribir {2}» si procede.", "Download abgeschlossen: {0} OK, {1} Fehler. Danach „{2} schreiben“, falls zutreffend.");
            E("Mods.ErrorPrefix", "Error: {0}", "Erreur : {0}", "Error: {0}", "Fehler: {0}");

            // ==== Notif ====
            E("Notif.Title", "Notifications", "Notifications", "Notificaciones", "Benachrichtigungen");
            E("Notif.Intro", "Global notification channels. All alerts (crash, RAM, disk, updates...) are broadcast here. Fill in a channel, check \"Enable\", then \"Test\".", "Canaux de notification globaux. Toutes les alertes (plantage, RAM, disque, mises à jour...) sont diffusées ici. Renseigne un canal, coche « Activer », puis « Tester ».", "Canales de notificación globales. Todas las alertas (fallos, RAM, disco, actualizaciones...) se difunden aquí. Rellena un canal, marca «Activar» y luego «Probar».", "Globale Benachrichtigungskanäle. Alle Warnungen (Absturz, RAM, Datenträger, Updates...) werden hier ausgegeben. Fülle einen Kanal aus, aktiviere „Aktivieren“ und dann „Testen“.");
            E("Notif.Enable", "Enable", "Activer", "Activar", "Aktivieren");
            E("Notif.TestChannel", "Test this channel", "Tester ce canal", "Probar este canal", "Diesen Kanal testen");
            E("Notif.Sending", "⏳ Sending a test message…", "⏳ Envoi d'un message de test…", "⏳ Enviando un mensaje de prueba…", "⏳ Testnachricht wird gesendet…");
            E("Notif.TestSubject", "Test WindowsGSM", "Test WindowsGSM", "Prueba WindowsGSM", "Test WindowsGSM");
            E("Notif.TestBody", "✅ This is a test message from WindowsGSM.", "✅ Ceci est un message de test depuis WindowsGSM.", "✅ Este es un mensaje de prueba de WindowsGSM.", "✅ Dies ist eine Testnachricht von WindowsGSM.");
            E("Notif.SentOk", "✅ Sent. Check that it was received.", "✅ Envoyé. Vérifie qu'il a bien été reçu.", "✅ Enviado. Comprueba que se ha recibido.", "✅ Gesendet. Prüfe, ob sie angekommen ist.");
            E("Notif.SentFail", "❌ Failed (channel disabled or incorrect fields?). See the AppLog.", "❌ Échec (canal désactivé ou champs incorrects ?). Consulte l'AppLog.", "❌ Error (¿canal desactivado o campos incorrectos?). Consulta el AppLog.", "❌ Fehlgeschlagen (Kanal deaktiviert oder falsche Felder?). Siehe AppLog.");
            E("Notif.ErrorPrefix", "❌ Error: {0}", "❌ Erreur : {0}", "❌ Error: {0}", "❌ Fehler: {0}");
            E("Notif.NtfyServer", "Server (URL)", "Serveur (URL)", "Servidor (URL)", "Server (URL)");
            E("Notif.NtfyTopic", "Topic", "Sujet (topic)", "Tema (topic)", "Thema (Topic)");
            E("Notif.NtfyToken", "Token (optional)", "Token (facultatif)", "Token (opcional)", "Token (optional)");
            E("Notif.NtfyPriority", "Priority (min/low/default/high/max)", "Priorité (min/low/default/high/max)", "Prioridad (min/low/default/high/max)", "Priorität (min/low/default/high/max)");
            E("Notif.TelegramBotToken", "Bot Token", "Bot Token", "Bot Token", "Bot Token");
            E("Notif.TelegramChatId", "Chat ID", "Chat ID", "Chat ID", "Chat ID");
            E("Notif.EmailTitle", "Email (SMTP)", "E-mail (SMTP)", "Correo (SMTP)", "E-Mail (SMTP)");
            E("Notif.EmailSmtpHost", "SMTP server", "Serveur SMTP", "Servidor SMTP", "SMTP-Server");
            E("Notif.EmailPort", "Port", "Port", "Puerto", "Port");
            E("Notif.EmailSsl", "SSL/TLS", "SSL/TLS", "SSL/TLS", "SSL/TLS");
            E("Notif.EmailUsername", "Username", "Nom d'utilisateur", "Nombre de usuario", "Benutzername");
            E("Notif.EmailPassword", "Password", "Mot de passe", "Contraseña", "Passwort");
            E("Notif.EmailFrom", "Sender (From)", "Expéditeur (From)", "Remitente (From)", "Absender (From)");
            E("Notif.EmailTo", "Recipient(s) (To)", "Destinataire(s) (To)", "Destinatario(s) (To)", "Empfänger (To)");
            E("Notif.WebhookTitle", "Generic webhook", "Webhook générique", "Webhook genérico", "Generischer Webhook");
            E("Notif.WebhookUrl", "URL", "URL", "URL", "URL");
            E("Notif.WebhookBearer", "Bearer (optional)", "Bearer (facultatif)", "Bearer (opcional)", "Bearer (optional)");

            // ==== Ports ====
            E("Ports.Title", "Ports / UPnP", "Ports / UPnP", "Puertos / UPnP", "Ports / UPnP");
            E("Ports.EnableUpnp", "Enable UPnP auto port-forward (opens/closes ports on the router at start/stop)", "Activer la redirection de ports automatique UPnP (ouvre/ferme les ports sur le routeur au démarrage/arrêt)", "Activar el reenvío automático de puertos UPnP (abre/cierra los puertos del router al iniciar/detener)", "Automatische UPnP-Portweiterleitung aktivieren (öffnet/schließt Ports am Router beim Starten/Stoppen)");
            E("Ports.Tip", "Tip: if UPnP is disabled on the router (e.g. OPNsense), leave unchecked and simply copy the ports listed below into your manual forward. RCON is never suggested enabled: only open it if necessary.", "Astuce : si UPnP est désactivé sur le routeur (ex. OPNsense), laisse décoché et recopie simplement les ports listés ci-dessous dans ta redirection manuelle. RCON n'est jamais suggéré activé : ne l'ouvre que si nécessaire.", "Consejo: si UPnP está desactivado en el router (p. ej. OPNsense), déjalo sin marcar y simplemente copia los puertos listados abajo en tu reenvío manual. RCON nunca se sugiere activado: ábrelo solo si es necesario.", "Tipp: Ist UPnP am Router deaktiviert (z. B. OPNsense), lasse das Kontrollkästchen leer und übernimm die unten aufgeführten Ports einfach in deine manuelle Weiterleitung. RCON wird nie standardmäßig aktiviert vorgeschlagen: öffne es nur, wenn nötig.");
            E("Ports.NoServer", "No server.", "Aucun serveur.", "Ningún servidor.", "Kein Server.");
            E("Ports.DeletePortTip", "Delete this port", "Supprimer ce port", "Eliminar este puerto", "Diesen Port löschen");
            E("Ports.AddLabel", "Add:", "Ajouter :", "Añadir:", "Hinzufügen:");
            E("Ports.ManualLabel", "Manual", "Manuel", "Manual", "Manuell");

            // ==== WebApi ====
            E("WebApi.Title", "Web API (remote control)", "API Web (contrôle à distance)", "API web (control remoto)", "Web-API (Fernsteuerung)");
            E("WebApi.Header", "Remote control (web server)", "Contrôle à distance (serveur web)", "Control remoto (servidor web)", "Fernsteuerung (Webserver)");
            E("WebApi.Intro", "Two independent parts you can toggle separately: the token API and the browser portal. The server runs as soon as at least one is enabled — no separate master switch.", "Deux parties indépendantes activables séparément : l'API à jeton et le portail navigateur. Le serveur démarre dès qu'au moins l'une est activée — pas d'interrupteur principal séparé.", "Dos partes independientes que puedes activar por separado: la API con token y el portal del navegador. El servidor se ejecuta en cuanto se activa al menos una — sin interruptor principal aparte.", "Zwei unabhängige Teile, die separat aktivierbar sind: die Token-API und das Browser-Portal. Der Server läuft, sobald mindestens einer aktiviert ist — kein separater Hauptschalter.");
            E("WebApi.EnableApi", "Enable the token API", "Activer l'API à jeton", "Activar la API con token", "Token-API aktivieren");
            E("WebApi.ApiRoutesHelp", "GET /api/servers · POST /api/servers/{id}/{start|stop|restart|backup}. Requires a Bearer token (below).", "GET /api/servers · POST /api/servers/{id}/{start|stop|restart|backup}. Nécessite un jeton Bearer (ci-dessous).", "GET /api/servers · POST /api/servers/{id}/{start|stop|restart|backup}. Requiere un token Bearer (abajo).", "GET /api/servers · POST /api/servers/{id}/{start|stop|restart|backup}. Erfordert ein Bearer-Token (unten).");
            E("WebApi.Port", "Port:", "Port :", "Puerto:", "Port:");
            E("WebApi.ListenIp", "Listen IP:", "IP d'écoute :", "IP de escucha:", "Lausch-IP:");
            E("WebApi.ListenIpHelp", "127.0.0.1 = this machine only (no admin/firewall needed) — use this if the client is local.\n0.0.0.0 / + = all interfaces (LAN/internet): requires running WGSM as administrator (or a netsh urlacl) and an open inbound firewall port.\nYou can also set a specific machine IP. NB: browsers cannot connect TO 0.0.0.0 — reach the server at 127.0.0.1 or the machine's real IP.", "127.0.0.1 = cette machine uniquement (ni admin ni pare-feu nécessaires) — à utiliser si le client est local.\n0.0.0.0 / + = toutes les interfaces (LAN/internet) : nécessite d'exécuter WGSM en administrateur (ou un netsh urlacl) et un port entrant ouvert dans le pare-feu.\nTu peux aussi indiquer une IP machine spécifique. NB : les navigateurs ne peuvent pas se connecter À 0.0.0.0 — joins le serveur via 127.0.0.1 ou l'IP réelle de la machine.", "127.0.0.1 = solo esta máquina (sin admin ni firewall) — úsalo si el cliente es local.\n0.0.0.0 / + = todas las interfaces (LAN/internet): requiere ejecutar WGSM como administrador (o un netsh urlacl) y un puerto entrante abierto en el firewall.\nTambién puedes indicar una IP concreta de la máquina. Nota: los navegadores no pueden conectarse A 0.0.0.0 — accede al servidor por 127.0.0.1 o la IP real de la máquina.", "127.0.0.1 = nur dieser Rechner (kein Admin/keine Firewall nötig) — nutze dies, wenn der Client lokal ist.\n0.0.0.0 / + = alle Schnittstellen (LAN/Internet): erfordert das Ausführen von WGSM als Administrator (oder ein netsh urlacl) und einen offenen eingehenden Firewall-Port.\nDu kannst auch eine bestimmte Rechner-IP angeben. Hinweis: Browser können sich nicht ZU 0.0.0.0 verbinden — erreiche den Server über 127.0.0.1 oder die echte IP des Rechners.");
            E("WebApi.TokenBearer", "Token (Bearer):", "Jeton (Bearer) :", "Token (Bearer):", "Token (Bearer):");
            E("WebApi.PortalHeader", "Web portal (browser interface)", "Portail web (interface navigateur)", "Portal web (interfaz de navegador)", "Web-Portal (Browser-Oberfläche)");
            E("WebApi.PortalHelp", "Login page + dashboard (start/stop/restart/backup) with accounts and roles. Auth via session cookie (HttpOnly, SameSite=Strict).", "Page de connexion + tableau de bord (start/stop/restart/backup) avec comptes et rôles. Authentification via cookie de session (HttpOnly, SameSite=Strict).", "Página de inicio de sesión + panel (start/stop/restart/backup) con cuentas y roles. Autenticación mediante cookie de sesión (HttpOnly, SameSite=Strict).", "Anmeldeseite + Dashboard (start/stop/restart/backup) mit Konten und Rollen. Authentifizierung über Sitzungscookie (HttpOnly, SameSite=Strict).");
            E("WebApi.EnablePortal", "Enable the web portal", "Activer le portail web", "Activar el portal web", "Web-Portal aktivieren");
            E("WebApi.DonatorFeature", "★ Donator feature.", "★ Fonction donateur.", "★ Función para donantes.", "★ Spender-Funktion.");
            E("WebApi.PortalPort", "Portal port:", "Port du portail :", "Puerto del portal:", "Portal-Port:");
            E("WebApi.Ip", "IP:", "IP :", "IP:", "IP:");
            E("WebApi.PortalPortHelp", "Independent of the API above. Same IP:port as the API = single shared listener. Use \"0.0.0.0\" or \"+\" for all interfaces (LAN/internet) — that requires running WGSM as administrator (or a netsh urlacl) and an open firewall port.", "Indépendant de l'API ci-dessus. Même IP:port que l'API = un seul écouteur partagé. Utilise \"0.0.0.0\" ou \"+\" pour toutes les interfaces (LAN/internet) — cela nécessite d'exécuter WGSM en administrateur (ou un netsh urlacl) et un port ouvert dans le pare-feu.", "Independiente de la API anterior. Misma IP:puerto que la API = un único listener compartido. Usa \"0.0.0.0\" o \"+\" para todas las interfaces (LAN/internet) — eso requiere ejecutar WGSM como administrador (o un netsh urlacl) y un puerto abierto en el firewall.", "Unabhängig von der API oben. Gleiche IP:Port wie die API = ein einziger gemeinsamer Listener. Verwende \"0.0.0.0\" oder \"+\" für alle Schnittstellen (LAN/Internet) — das erfordert das Ausführen von WGSM als Administrator (oder ein netsh urlacl) und einen offenen Firewall-Port.");
            E("WebApi.PortalDonatorFeatureName", "Web portal (authentication + roles)", "Portail web (authentification + rôles)", "Portal web (autenticación + roles)", "Web-Portal (Authentifizierung + Rollen)");
            E("WebApi.WebAccounts", "Web accounts…", "Comptes web…", "Cuentas web…", "Web-Konten…");
            E("WebApi.CookieSecure", "\"Secure\" session cookie (behind an HTTPS proxy)", "Cookie de session « Secure » (derrière un proxy HTTPS)", "Cookie de sesión «Secure» (detrás de un proxy HTTPS)", "„Secure“-Sitzungscookie (hinter einem HTTPS-Proxy)");
            E("WebApi.SecurityBestPractices", "🔒 Security best practices (OWASP):\n• The API is plain HTTP → for internet exposure, put it BEHIND AN HTTPS REVERSE-PROXY (nginx/Caddy/Traefik) that handles TLS; ideally keep listening on 127.0.0.1 and let the proxy talk to the LAN/internet. Then enable \"Secure cookie\".\n• Long random token (\"Generate\" button); never share it and rotate it regularly. (The token is NOT accepted in the URL.)\n• Restrict access at the firewall (only open the port to trusted IPs); add rate-limiting/Fail2ban on the proxy side.\n• Built in: PBKDF2 passwords, HttpOnly+SameSite=Strict cookie sessions, anti-CSRF (Origin check), hardened headers (CSP, nosniff, X-Frame-Options DENY, Permissions-Policy, hidden Server header), brute-force throttle (10 fails/5 min), strict action validation, audit log of logins/actions.\n• Listening outside 127.0.0.1 requires WGSM as administrator (or \"netsh http add urlacl\").", "🔒 Bonnes pratiques de sécurité (OWASP) :\n• L'API est en HTTP clair → pour une exposition sur internet, place-la DERRIÈRE UN REVERSE-PROXY HTTPS (nginx/Caddy/Traefik) qui gère le TLS ; idéalement, garde l'écoute sur 127.0.0.1 et laisse le proxy dialoguer avec le LAN/internet. Active ensuite « Secure cookie ».\n• Jeton long et aléatoire (bouton « Generate ») ; ne le partage jamais et fais-le tourner régulièrement. (Le jeton n'est PAS accepté dans l'URL.)\n• Restreins l'accès au pare-feu (n'ouvre le port qu'à des IP de confiance) ; ajoute du rate-limiting/Fail2ban côté proxy.\n• Intégré : mots de passe PBKDF2, sessions par cookie HttpOnly+SameSite=Strict, anti-CSRF (vérification Origin), en-têtes durcis (CSP, nosniff, X-Frame-Options DENY, Permissions-Policy, en-tête Server masqué), limitation anti-brute-force (10 échecs/5 min), validation stricte des actions, journal d'audit des connexions/actions.\n• Écouter en dehors de 127.0.0.1 nécessite WGSM en administrateur (ou « netsh http add urlacl »).", "🔒 Buenas prácticas de seguridad (OWASP):\n• La API es HTTP sin cifrar → para exponerla a internet, colócala DETRÁS DE UN PROXY INVERSO HTTPS (nginx/Caddy/Traefik) que gestione el TLS; lo ideal es seguir escuchando en 127.0.0.1 y dejar que el proxy hable con la LAN/internet. Después activa «Secure cookie».\n• Token largo y aleatorio (botón «Generate»); no lo compartas nunca y rótalo con regularidad. (El token NO se acepta en la URL.)\n• Restringe el acceso en el firewall (abre el puerto solo a IP de confianza); añade rate-limiting/Fail2ban en el lado del proxy.\n• Incorporado: contraseñas PBKDF2, sesiones por cookie HttpOnly+SameSite=Strict, anti-CSRF (comprobación de Origin), cabeceras reforzadas (CSP, nosniff, X-Frame-Options DENY, Permissions-Policy, cabecera Server oculta), limitación anti-fuerza bruta (10 fallos/5 min), validación estricta de acciones, registro de auditoría de inicios de sesión/acciones.\n• Escuchar fuera de 127.0.0.1 requiere WGSM como administrador (o «netsh http add urlacl»).", "🔒 Sicherheits-Best-Practices (OWASP):\n• Die API läuft über einfaches HTTP → für die Internet-Freigabe HINTER EINEN HTTPS-REVERSE-PROXY (nginx/Caddy/Traefik) setzen, der TLS übernimmt; idealerweise weiter auf 127.0.0.1 lauschen und den Proxy mit LAN/Internet kommunizieren lassen. Dann „Secure cookie“ aktivieren.\n• Langes, zufälliges Token (Schaltfläche „Generate“); niemals weitergeben und regelmäßig rotieren. (Das Token wird NICHT in der URL akzeptiert.)\n• Zugriff an der Firewall beschränken (Port nur für vertrauenswürdige IPs öffnen); Rate-Limiting/Fail2ban auf der Proxy-Seite ergänzen.\n• Integriert: PBKDF2-Passwörter, HttpOnly+SameSite=Strict-Cookie-Sitzungen, Anti-CSRF (Origin-Prüfung), gehärtete Header (CSP, nosniff, X-Frame-Options DENY, Permissions-Policy, verborgener Server-Header), Brute-Force-Drosselung (10 Fehlversuche/5 Min.), strenge Aktionsvalidierung, Audit-Protokoll für Anmeldungen/Aktionen.\n• Das Lauschen außerhalb von 127.0.0.1 erfordert WGSM als Administrator (oder „netsh http add urlacl“).");
            E("WebApi.SaveApply", "Save & apply", "Enregistrer et appliquer", "Guardar y aplicar", "Speichern & anwenden");
            E("WebApi.NeedToken", "Set a token (or click \"Generate\") to enable the API.", "Définis un jeton (ou clique sur « Generate ») pour activer l'API.", "Establece un token (o pulsa «Generate») para activar la API.", "Lege ein Token fest (oder klicke auf „Generate“), um die API zu aktivieren.");
            E("WebApi.NeedAccount", "Create at least one account (\"Web accounts…\") before enabling the portal.", "Crée au moins un compte (« Comptes web… ») avant d'activer le portail.", "Crea al menos una cuenta («Cuentas web…») antes de activar el portal.", "Erstelle mindestens ein Konto („Web-Konten…“), bevor du das Portal aktivierst.");
            E("WebApi.InvalidApiPort", "Invalid API port.", "Port d'API invalide.", "Puerto de la API no válido.", "Ungültiger API-Port.");
            E("WebApi.InvalidPortalPort", "Invalid portal port.", "Port du portail invalide.", "Puerto del portal no válido.", "Ungültiger Portal-Port.");
            E("WebApi.StatusNothing", "✔ Nothing enabled (set a token and/or enable the portal).", "✔ Rien d'activé (définis un jeton et/ou active le portail).", "✔ Nada activado (establece un token o activa el portal).", "✔ Nichts aktiviert (lege ein Token fest und/oder aktiviere das Portal).");
            E("WebApi.StatusPortal", "✔ Started. Web portal: http://{0}:{1}/ (sign in with an account).", "✔ Démarré. Portail web : http://{0}:{1}/ (connecte-toi avec un compte).", "✔ Iniciado. Portal web: http://{0}:{1}/ (inicia sesión con una cuenta).", "✔ Gestartet. Web-Portal: http://{0}:{1}/ (mit einem Konto anmelden).");
            E("WebApi.StatusApi", "✔ API started. Test: GET http://{0}:{1}/api/servers (header Authorization: Bearer <token>).", "✔ API démarrée. Test : GET http://{0}:{1}/api/servers (en-tête Authorization: Bearer <token>).", "✔ API iniciada. Prueba: GET http://{0}:{1}/api/servers (cabecera Authorization: Bearer <token>).", "✔ API gestartet. Test: GET http://{0}:{1}/api/servers (Header Authorization: Bearer <token>).");

            // ==== MainWindow (MW.*) ====
            E("MW.Common.Save", "Save", "Enregistrer", "Guardar", "Speichern");
            E("MW.Common.Cancel", "Cancel", "Annuler", "Cancelar", "Abbrechen");
            E("MW.Common.Close", "Close", "Fermer", "Cerrar", "Schließen");
            E("MW.Common.Apply", "Apply", "Appliquer", "Aplicar", "Übernehmen");
            E("MW.Common.Edit", "Edit", "Modifier", "Editar", "Bearbeiten");
            E("MW.Common.Remove", "Remove", "Supprimer", "Quitar", "Entfernen");
            E("MW.Common.Delete", "Delete", "Supprimer", "Eliminar", "Löschen");
            E("MW.Common.Restore", "Restore", "Restaurer", "Restaurar", "Wiederherstellen");
            E("MW.Common.Browse", "Browse", "Parcourir", "Examinar", "Durchsuchen");
            E("MW.Common.Clear", "CLEAR", "EFFACER", "BORRAR", "LEEREN");
            E("MW.TitleBar.Website", "Website", "Site web", "Sitio web", "Website");
            E("MW.TitleBar.Hide", "Hide", "Masquer", "Ocultar", "Ausblenden");
            E("MW.TokenHelp.Title", "Create a Discord bot token", "Créer un token de bot Discord", "Crear un token de bot de Discord", "Discord-Bot-Token erstellen");
            E("MW.TokenHelp.Step1", "1.  Open the Discord Developer Portal and sign in.", "1.  Ouvre le Discord Developer Portal et connecte-toi.", "1.  Abre el Discord Developer Portal e inicia sesión.", "1.  Öffne das Discord Developer Portal und melde dich an.");
            E("MW.TokenHelp.Step2", "2.  \"New Application\" → give it a name → Create.", "2.  « New Application » → donne-lui un nom → Create.", "2.  «New Application» → ponle un nombre → Create.", "2.  „New Application“ → gib ihr einen Namen → Create.");
            E("MW.TokenHelp.Step3", "3.  \"Bot\" tab → \"Reset Token\" → copy the token (shown only once).", "3.  Onglet « Bot » → « Reset Token » → copie le token (affiché une seule fois).", "3.  Pestaña «Bot» → «Reset Token» → copia el token (se muestra una sola vez).", "3.  Reiter „Bot“ → „Reset Token“ → kopiere den Token (wird nur einmal angezeigt).");
            E("MW.TokenHelp.Step4", "4.  Still in \"Bot\" → enable \"MESSAGE CONTENT INTENT\" (required to read commands).", "4.  Toujours dans « Bot » → active « MESSAGE CONTENT INTENT » (requis pour lire les commandes).", "4.  Aún en «Bot» → activa «MESSAGE CONTENT INTENT» (necesario para leer los comandos).", "4.  Weiterhin in „Bot“ → aktiviere „MESSAGE CONTENT INTENT“ (nötig, um Befehle zu lesen).");
            E("MW.TokenHelp.Step5", "5.  Paste the token into WindowsGSM (Edit → paste → Save), then enable the bot.", "5.  Colle le token dans WindowsGSM (Modifier → coller → Enregistrer), puis active le bot.", "5.  Pega el token en WindowsGSM (Editar → pegar → Guardar), luego activa el bot.", "5.  Füge den Token in WindowsGSM ein (Bearbeiten → einfügen → Speichern) und aktiviere dann den Bot.");
            E("MW.TokenHelp.Step6", "6.  Click \"Invite\" to add the bot to your server, then put your Discord ID in the Admin List.", "6.  Clique sur « Invite » pour ajouter le bot à ton serveur, puis mets ton ID Discord dans la liste des admins.", "6.  Haz clic en «Invite» para añadir el bot a tu servidor, luego pon tu ID de Discord en la lista de administradores.", "6.  Klicke auf „Invite“, um den Bot zu deinem Server hinzuzufügen, und trage dann deine Discord-ID in die Admin-Liste ein.");
            E("MW.TokenHelp.Warn", "⚠ Keep your token secret. If it leaks, use \"Reset Token\" in the portal.", "⚠ Garde ton token secret. En cas de fuite, utilise « Reset Token » dans le portail.", "⚠ Mantén tu token en secreto. Si se filtra, usa «Reset Token» en el portal.", "⚠ Halte deinen Token geheim. Bei einem Leck nutze „Reset Token“ im Portal.");
            E("MW.TokenHelp.OpenPortal", "Open the Discord Portal", "Ouvrir le portail Discord", "Abrir el portal de Discord", "Discord-Portal öffnen");
            E("MW.DiscordAdmin.TitleAdd", "Add a Discord admin", "Ajouter un admin Discord", "Añadir un administrador de Discord", "Discord-Admin hinzufügen");
            E("MW.DiscordAdmin.UserId", "User's Discord ID", "ID Discord de l'utilisateur", "ID de Discord del usuario", "Discord-ID des Benutzers");
            E("MW.DiscordAdmin.Verify", "Verify", "Vérifier", "Verificar", "Prüfen");
            E("MW.DiscordAdmin.Tip", "Tip: Discord → Settings → Advanced → Developer Mode. Then right-click the user → \"Copy ID\".", "Astuce : Discord → Settings → Advanced → Developer Mode. Puis clic droit sur l'utilisateur → « Copy ID ».", "Consejo: Discord → Settings → Advanced → Developer Mode. Luego clic derecho en el usuario → «Copy ID».", "Tipp: Discord → Settings → Advanced → Developer Mode. Dann Rechtsklick auf den Benutzer → „Copy ID“.");
            E("MW.DiscordAdmin.AllServers", "All servers (full access)", "Tous les serveurs (accès complet)", "Todos los servidores (acceso total)", "Alle Server (Vollzugriff)");
            E("MW.DiscordAdmin.ChooseServers", "Otherwise, choose the allowed servers:", "Sinon, choisis les serveurs autorisés :", "Si no, elige los servidores permitidos:", "Andernfalls wähle die erlaubten Server:");
            E("MW.Crontab.Title", "Wizard — restart schedule", "Assistant — planification du redémarrage", "Asistente — programación de reinicio", "Assistent — Neustartplanung");
            E("MW.Crontab.Frequency", "Frequency", "Fréquence", "Frecuencia", "Häufigkeit");
            E("MW.Crontab.EveryDay", "Every day", "Chaque jour", "Cada día", "Täglich");
            E("MW.Crontab.EveryWeek", "Every week", "Chaque semaine", "Cada semana", "Wöchentlich");
            E("MW.Crontab.Day", "Day", "Jour", "Día", "Tag");
            E("MW.Crontab.Time", "Time", "Heure", "Hora", "Uhrzeit");
            E("MW.Day.Monday", "Monday", "Lundi", "Lunes", "Montag");
            E("MW.Day.Tuesday", "Tuesday", "Mardi", "Martes", "Dienstag");
            E("MW.Day.Wednesday", "Wednesday", "Mercredi", "Miércoles", "Mittwoch");
            E("MW.Day.Thursday", "Thursday", "Jeudi", "Jueves", "Donnerstag");
            E("MW.Day.Friday", "Friday", "Vendredi", "Viernes", "Freitag");
            E("MW.Day.Saturday", "Saturday", "Samedi", "Sábado", "Samstag");
            E("MW.Day.Sunday", "Sunday", "Dimanche", "Domingo", "Sonntag");
            E("MW.Plugins.Installed", "Installed:", "Installés :", "Instalados:", "Installiert:");
            E("MW.Plugins.Loaded", "Loaded:", "Chargés :", "Cargados:", "Geladen:");
            E("MW.Plugins.Failed", "Failed:", "Échecs :", "Fallidos:", "Fehlgeschlagen:");
            E("MW.Plugins.Import", "Import Plugin", "Importer un plugin", "Importar plugin", "Plugin importieren");
            E("MW.Plugins.Reload", "Reload Plugins", "Recharger les plugins", "Recargar plugins", "Plugins neu laden");
            E("MW.Plugins.LoadedList", "Loaded Plugin List", "Liste des plugins chargés", "Lista de plugins cargados", "Liste geladener Plugins");
            E("MW.Settings.HardwareAcceleration", "Hardware Acceleration", "Accélération matérielle", "Aceleración por hardware", "Hardwarebeschleunigung");
            E("MW.Settings.UIAnimation", "UI Animation", "Animation de l'interface", "Animación de la interfaz", "UI-Animation");
            E("MW.Settings.DarkTheme", "Dark Theme", "Thème sombre", "Tema oscuro", "Dunkles Design");
            E("MW.Settings.StartOnLogin", "Start WindowsGSM on Login", "Démarrer WindowsGSM à la connexion", "Iniciar WindowsGSM al iniciar sesión", "WindowsGSM bei Anmeldung starten");
            E("MW.Settings.RestartOnCrash", "Auto Restart WindowsGSM on Crash", "Redémarrage auto de WindowsGSM en cas de plantage", "Reiniciar WindowsGSM automáticamente al fallar", "WindowsGSM bei Absturz automatisch neu starten");
            E("MW.Settings.SendStatistics", "Send Statistics", "Envoyer des statistiques", "Enviar estadísticas", "Statistiken senden");
            E("MW.Settings.DonorConnect", "Donor Connect (Patreon)", "Connexion donateur (Patreon)", "Conexión de donante (Patreon)", "Spender-Verbindung (Patreon)");
            E("MW.Settings.ThemeDonorOnly", "WindowsGSM Theme (Donor Only)", "Thème WindowsGSM (donateurs uniquement)", "Tema de WindowsGSM (solo donantes)", "WindowsGSM-Design (nur Spender)");
            E("MW.Alert.AutoStart", "Auto Start Alert", "Alerte démarrage auto", "Alerta de inicio automático", "Auto-Start-Benachrichtigung");
            E("MW.Alert.AutoRestart", "Auto Restart Alert", "Alerte redémarrage auto", "Alerta de reinicio automático", "Auto-Neustart-Benachrichtigung");
            E("MW.Alert.AutoUpdate", "Auto Update Alert", "Alerte mise à jour auto", "Alerta de actualización automática", "Auto-Update-Benachrichtigung");
            E("MW.Alert.RestartCrontab", "Restart Crontab Alert", "Alerte planification de redémarrage", "Alerta de reinicio programado", "Neustartplan-Benachrichtigung");
            E("MW.Alert.Crash", "Crash Alert", "Alerte de plantage", "Alerta de fallo", "Absturz-Benachrichtigung");
            E("MW.Restore.ServerLabel", "Server:", "Serveur :", "Servidor:", "Server:");
            E("MW.Restore.SelectBackup", "Please select a backup", "Sélectionne une sauvegarde", "Selecciona una copia de seguridad", "Bitte eine Sicherung auswählen");
            E("MW.EditConfig.ServerID", "Server ID", "ID du serveur", "ID del servidor", "Server-ID");
            E("MW.EditConfig.ServerGame", "Server Game", "Jeu du serveur", "Juego del servidor", "Server-Spiel");
            E("MW.EditConfig.ServerName", "Server Name", "Nom du serveur", "Nombre del servidor", "Servername");
            E("MW.EditConfig.ServerIP", "Server IP Address", "Adresse IP du serveur", "Dirección IP del servidor", "Server-IP-Adresse");
            E("MW.EditConfig.ServerPort", "Server Port", "Port du serveur", "Puerto del servidor", "Server-Port");
            E("MW.EditConfig.ServerQueryPort", "Server Query Port", "Port de requête du serveur", "Puerto de consulta del servidor", "Server-Query-Port");
            E("MW.EditConfig.ServerMaxplayer", "Server Maxplayer", "Joueurs max du serveur", "Máx. de jugadores del servidor", "Max. Spieler des Servers");
            E("MW.EditConfig.ServerStartMap", "Server Start Map", "Carte de démarrage du serveur", "Mapa inicial del servidor", "Start-Map des Servers");
            E("MW.EditConfig.ServerGSLT", "Server GSLT", "GSLT du serveur", "GSLT del servidor", "Server-GSLT");
            E("MW.EditConfig.ServerStartParam", "Server Start Param", "Paramètres de démarrage du serveur", "Parámetros de inicio del servidor", "Server-Startparameter");
            E("MW.Addons.Name", "Name: ", "Nom : ", "Nombre: ", "Name: ");
            E("MW.Addons.Game", "Game: ", "Jeu : ", "Juego: ", "Spiel: ");
            E("MW.Addons.Type", "Type: ", "Type : ", "Tipo: ", "Typ: ");
            E("MW.Addons.DisabledHint", "Disabled - Double click item to activate", "Désactivés - Double-clique un élément pour l'activer", "Desactivados - Doble clic para activar", "Deaktiviert – Doppelklick zum Aktivieren");
            E("MW.Addons.ActivatedHint", "Activated - Double click item to disable", "Activés - Double-clique un élément pour le désactiver", "Activados - Doble clic para desactivar", "Aktiviert – Doppelklick zum Deaktivieren");
            E("MW.Install.GameServer", "Game Server", "Serveur de jeu", "Servidor de juego", "Spielserver");
            E("MW.Install.ServerName", "Server Name", "Nom du serveur", "Nombre del servidor", "Servername");
            E("MW.Install.SetAccount", "Set Account", "Définir le compte", "Configurar cuenta", "Konto festlegen");
            E("MW.Install.Install", "Install", "Installer", "Instalar", "Installieren");
            E("MW.Install.Progress", "Progress", "Progression", "Progreso", "Fortschritt");
            E("MW.Install.Log", "Install Log", "Journal d'installation", "Registro de instalación", "Installationsprotokoll");
            E("MW.Install.SendToken", "Send Token", "Envoyer le token", "Enviar token", "Token senden");
            E("MW.Import.OldServerDir", "Old Server Directory:", "Ancien dossier du serveur :", "Carpeta del servidor anterior:", "Altes Server-Verzeichnis:");
            E("MW.Import.Import", "Import", "Importer", "Importar", "Importieren");
            E("MW.Bot.Heading", "DISCORD BOT", "BOT DISCORD", "BOT DE DISCORD", "DISCORD-BOT");
            E("MW.Bot.Usage", "Usage: Remote control the game servers with Discord", "Usage : contrôler les serveurs de jeu à distance avec Discord", "Uso: controlar los servidores de juego de forma remota con Discord", "Verwendung: Spielserver aus der Ferne mit Discord steuern");
            E("MW.Bot.Invite", "Invite", "Inviter", "Invitar", "Einladen");
            E("MW.Bot.AvailableCommands", "Available commands:", "Commandes disponibles :", "Comandos disponibles:", "Verfügbare Befehle:");
            E("MW.Bot.Enable", "Enable", "Activer", "Activar", "Aktivieren");
            E("MW.Toggle.AutoStart", "Auto Start", "Démarrage auto", "Inicio automático", "Auto-Start");
            E("MW.Bot.Prefix", "Bot Prefix", "Préfixe du bot", "Prefijo del bot", "Bot-Präfix");
            E("MW.Bot.Token", "Discord Bot Token", "Token du bot Discord", "Token del bot de Discord", "Discord-Bot-Token");
            E("MW.Bot.HowToToken", "How to get a token?", "Comment obtenir un token ?", "¿Cómo obtener un token?", "Wie bekomme ich einen Token?");
            E("MW.Bot.DashboardChannels", "Dashboard Channel ID(s)", "ID de salon(s) du tableau de bord", "ID de canal(es) del panel", "Dashboard-Kanal-ID(s)");
            E("MW.Bot.DashboardChannelsTip", "One or more channels (one per Discord server), separated by commas", "Un ou plusieurs salons (un par serveur Discord), séparés par des virgules", "Uno o varios canales (uno por servidor de Discord), separados por comas", "Ein oder mehrere Kanäle (einer pro Discord-Server), durch Kommas getrennt");
            E("MW.Bot.RefreshSec", "Refresh (sec)", "Rafraîchissement (s)", "Actualización (s)", "Aktualisierung (Sek.)");
            E("MW.Bot.AdminPanelChannels", "Admin Panel Channel ID(s)", "ID de salon(s) du panneau d'administration", "ID de canal(es) del panel de administración", "Admin-Panel-Kanal-ID(s)");
            E("MW.Bot.AdminPanelChannelsTip", "Channel dedicated to administration (one per Discord server), separated by commas. The bot maintains an interactive panel there (dropdown menu + buttons).", "Salon dédié à l'administration (un par serveur Discord), séparés par des virgules. Le bot y maintient un panneau interactif (menu déroulant + boutons).", "Canal dedicado a la administración (uno por servidor de Discord), separados por comas. El bot mantiene ahí un panel interactivo (menú desplegable + botones).", "Kanal für die Administration (einer pro Discord-Server), durch Kommas getrennt. Der Bot betreibt dort ein interaktives Panel (Dropdown-Menü + Schaltflächen).");
            E("MW.Bot.Log", "Discord Bot Log", "Journal du bot Discord", "Registro del bot de Discord", "Discord-Bot-Protokoll");
            E("MW.Bot.AdminList", "Admin List", "Liste des admins", "Lista de administradores", "Admin-Liste");
            E("MW.Bot.AddAdminID", "Add Admin ID", "Ajouter un ID admin", "Añadir ID de admin", "Admin-ID hinzufügen");
            E("MW.Bot.EditServerID", "Edit Server ID", "Modifier l'ID de serveur", "Editar ID de servidor", "Server-ID bearbeiten");
            E("MW.Bot.Col.AdminID", "Admin ID", "ID admin", "ID de admin", "Admin-ID");
            E("MW.Bot.Col.User", "User", "Utilisateur", "Usuario", "Benutzer");
            E("MW.Bot.Col.ServerIDs", "Server IDs", "ID de serveurs", "ID de servidores", "Server-IDs");
            E("MW.Dash.ServerStatus", "Server status", "État du serveur", "Estado del servidor", "Serverstatus");
            E("MW.Dash.Servers", "SERVERS", "SERVEURS", "SERVIDORES", "SERVER");
            E("MW.Dash.CPU", "CPU", "CPU", "CPU", "CPU");
            E("MW.Dash.RAM", "RAM", "RAM", "RAM", "RAM");
            E("MW.Dash.Players", "Players", "Joueurs", "Jugadores", "Spieler");
            E("MW.Dash.SystemMetrics", "SYSTEM METRICS", "MÉTRIQUES SYSTÈME", "MÉTRICAS DEL SISTEMA", "SYSTEMMETRIKEN");
            E("MW.Dash.Memory", "Memory", "Mémoire", "Memoria", "Arbeitsspeicher");
            E("MW.Dash.Disk", "Disk", "Disque", "Disco", "Datenträger");
            E("MW.Dash.GameServers", "GAME SERVERS", "SERVEURS DE JEU", "SERVIDORES DE JUEGO", "SPIELSERVER");
            E("MW.Dash.ServersBig", "Servers", "Serveurs", "Servidores", "Server");
            E("MW.Dash.InstalledCount", "Installed server count", "Nombre de serveurs installés", "Número de servidores instalados", "Anzahl installierter Server");
            E("MW.Dash.Online", "Online", "En ligne", "En línea", "Online");
            E("MW.Dash.StartedCount", "Started server count", "Nombre de serveurs démarrés", "Número de servidores iniciados", "Anzahl gestarteter Server");
            E("MW.Dash.ActivePlayers", "Active Players", "Joueurs actifs", "Jugadores activos", "Aktive Spieler");
            E("MW.Menu.Servers", "Servers", "Serveurs", "Servidores", "Server");
            E("MW.Menu.InstallGameServer", "Install GameServer", "Installer un serveur de jeu", "Instalar servidor de juego", "Spielserver installieren");
            E("MW.Menu.AddSteamServer", "Add a Steam server (AppID)…", "Ajouter un serveur Steam (AppID)…", "Añadir un servidor de Steam (AppID)…", "Steam-Server hinzufügen (AppID)…");
            E("MW.Menu.ImportGameServer", "Import GameServer", "Importer un serveur de jeu", "Importar servidor de juego", "Spielserver importieren");
            E("MW.Menu.DuplicateGameServer", "Duplicate GameServer", "Dupliquer le serveur de jeu", "Duplicar servidor de juego", "Spielserver duplizieren");
            E("MW.Menu.DeleteGameServer", "Delete GameServer", "Supprimer le serveur de jeu", "Eliminar servidor de juego", "Spielserver löschen");
            E("MW.Menu.Actions", "Actions", "Actions", "Acciones", "Aktionen");
            E("MW.Menu.Start", "Start", "Démarrer", "Iniciar", "Starten");
            E("MW.Menu.Stop", "Stop", "Arrêter", "Detener", "Stoppen");
            E("MW.Menu.Restart", "Restart", "Redémarrer", "Reiniciar", "Neu starten");
            E("MW.Menu.More", "More...", "Plus...", "Más...", "Mehr...");
            E("MW.Menu.StartAll", "Start All Servers", "Démarrer tous les serveurs", "Iniciar todos los servidores", "Alle Server starten");
            E("MW.Menu.StartAutoStart", "Start Servers with Auto Start Enabled", "Démarrer les serveurs avec le démarrage auto activé", "Iniciar servidores con inicio automático activado", "Server mit aktiviertem Auto-Start starten");
            E("MW.Menu.StopAll", "Stop All Servers", "Arrêter tous les serveurs", "Detener todos los servidores", "Alle Server stoppen");
            E("MW.Menu.RestartAll", "Restart All Servers", "Redémarrer tous les serveurs", "Reiniciar todos los servidores", "Alle Server neu starten");
            E("MW.Menu.ToggleConsole", "Toggle Console", "Basculer la console", "Alternar consola", "Konsole umschalten");
            E("MW.Menu.Update", "Update", "Mise à jour", "Actualizar", "Aktualisieren");
            E("MW.Menu.UpdateRun", "Update", "Mettre à jour", "Actualizar", "Aktualisieren");
            E("MW.Menu.UpdateValidate", "Update Validate", "Mise à jour + validation", "Actualizar y validar", "Aktualisieren + Prüfen");
            E("MW.Menu.UpdateAll", "Update ALL (servers with update available)", "Tout mettre à jour (serveurs avec mise à jour disponible)", "Actualizar TODO (servidores con actualización disponible)", "ALLE aktualisieren (Server mit verfügbarem Update)");
            E("MW.Menu.Backup", "Backup", "Sauvegarder", "Copia de seguridad", "Sicherung");
            E("MW.Menu.BackupAll", "Backup ALL (all servers)", "Tout sauvegarder (tous les serveurs)", "Copia de seguridad de TODO (todos los servidores)", "ALLE sichern (alle Server)");
            E("MW.Menu.MaintenanceMode", "Maintenance mode (toggle, selected server)", "Mode maintenance (bascule, serveur sélectionné)", "Modo mantenimiento (alternar, servidor seleccionado)", "Wartungsmodus (umschalten, ausgewählter Server)");
            E("MW.Menu.RestoreBackup", "Restore Backup", "Restaurer une sauvegarde", "Restaurar copia de seguridad", "Sicherung wiederherstellen");
            E("MW.Menu.Browse", "Browse", "Parcourir", "Explorar", "Durchsuchen");
            E("MW.Menu.ServerBackups", "Server Backups", "Sauvegardes du serveur", "Copias de seguridad del servidor", "Server-Sicherungen");
            E("MW.Menu.BackupFiles", "Backup Files", "Fichiers de sauvegarde", "Archivos de copia de seguridad", "Sicherungsdateien");
            E("MW.Menu.BackupConfigs", "Backup Configs", "Configs de sauvegarde", "Configuraciones de copia de seguridad", "Sicherungskonfigurationen");
            E("MW.Menu.ServerFiles", "Server Files", "Fichiers du serveur", "Archivos del servidor", "Serverdateien");
            E("MW.Menu.ServerConfigs", "Server Configs", "Configs du serveur", "Configuraciones del servidor", "Serverkonfigurationen");
            E("MW.Menu.ActionHistory", "Action History", "Historique des actions", "Historial de acciones", "Aktionsverlauf");
            E("MW.Menu.UptimeStats", "Uptime Statistics", "Statistiques de disponibilité", "Estadísticas de tiempo activo", "Betriebszeit-Statistiken");
            E("MW.Menu.Tools", "Tools", "Outils", "Herramientas", "Werkzeuge");
            E("MW.Menu.GlobalServerListCheck", "Global Server List Check", "Vérification de la liste globale des serveurs", "Comprobación de la lista global de servidores", "Globale Serverlisten-Prüfung");
            E("MW.Menu.ApiToken", "API Token (selected server)…", "Token API (serveur sélectionné)…", "Token de API (servidor seleccionado)…", "API-Token (ausgewählter Server)…");
            E("MW.Menu.InstallAddons", "Install Addons", "Installer des addons", "Instalar complementos", "Add-ons installieren");
            E("MW.Menu.Help", "Help", "Aide", "Ayuda", "Hilfe");
            E("MW.Menu.OnlineDocumentation", "Online Documentation", "Documentation en ligne", "Documentación en línea", "Online-Dokumentation");
            E("MW.Menu.ReportIssue", "Report an issue", "Signaler un problème", "Informar de un problema", "Problem melden");
            E("MW.Menu.SoftwareUpdates", "Software Updates", "Mises à jour du logiciel", "Actualizaciones del software", "Software-Updates");
            E("MW.Menu.About", "About WindowsGSM", "À propos de WindowsGSM", "Acerca de WindowsGSM", "Über WindowsGSM");
            E("MW.Home.SelectHint", "Select or Install or Import a server", "Sélectionne, installe ou importe un serveur", "Selecciona, instala o importa un servidor", "Server auswählen, installieren oder importieren");
            E("MW.Home.SearchPlaceholder", "Search a server (name, game, status)…", "Rechercher un serveur (nom, jeu, état)…", "Buscar un servidor (nombre, juego, estado)…", "Server suchen (Name, Spiel, Status)…");
            E("MW.Toolbar.Start", "START", "DÉMARRER", "INICIAR", "STARTEN");
            E("MW.Toolbar.Stop", "STOP", "ARRÊTER", "DETENER", "STOPPEN");
            E("MW.Toolbar.Restart", "RESTART", "REDÉMARRER", "REINICIAR", "NEU STARTEN");
            E("MW.Toolbar.Kill", "KILL", "TUER", "MATAR", "BEENDEN");
            E("MW.Toolbar.ToggleConsole", "TOGGLE CONSOLE", "BASCULER CONSOLE", "ALTERNAR CONSOLA", "KONSOLE UMSCHALTEN");
            E("MW.Toolbar.Update", "UPDATE", "MISE À JOUR", "ACTUALIZAR", "AKTUALISIEREN");
            E("MW.Toolbar.Backup", "BACKUP", "SAUVEGARDE", "COPIA DE SEGURIDAD", "SICHERUNG");
            E("MW.Toolbar.ManageAddons", "MANAGE ADDONS", "GÉRER LES ADDONS", "GESTIONAR COMPLEMENTOS", "ADD-ONS VERWALTEN");
            E("MW.Toolbar.Config", "CONFIG", "CONFIG", "CONFIG", "KONFIG");
            E("MW.Toolbar.Mods", "MODS", "MODS", "MODS", "MODS");
            E("MW.Col.Status", "Status", "État", "Estado", "Status");
            E("MW.Col.ServerName", "Server Name", "Nom du serveur", "Nombre del servidor", "Servername");
            E("MW.Col.IPAddress", "IP Address", "Adresse IP", "Dirección IP", "IP-Adresse");
            E("MW.Col.Port", "Port", "Port", "Puerto", "Port");
            E("MW.Col.QueryPort", "Query Port", "Port de requête", "Puerto de consulta", "Query-Port");
            E("MW.Col.Map", "Map", "Carte", "Mapa", "Map");
            E("MW.Col.Players", "Players", "Joueurs", "Jugadores", "Spieler");
            E("MW.Col.OnlinePlayers", "Online Players", "Joueurs en ligne", "Jugadores en línea", "Spieler online");
            E("MW.Col.OnlinePlayersTip", "Connected players (A2S query)", "Joueurs connectés (requête A2S)", "Jugadores conectados (consulta A2S)", "Verbundene Spieler (A2S-Abfrage)");
            E("MW.Col.CPU", "CPU", "CPU", "CPU", "CPU");
            E("MW.Col.RAM", "RAM", "RAM", "RAM", "RAM");
            E("MW.Col.Uptime", "Uptime", "Disponibilité", "Tiempo activo", "Betriebszeit");
            E("MW.Panel.ProcessPriority", "Process Priority", "Priorité du processus", "Prioridad del proceso", "Prozesspriorität");
            E("MW.Panel.SetAffinity", "Set Affinity", "Définir l'affinité", "Establecer afinidad", "Affinität festlegen");
            E("MW.Panel.EditConfig", "Edit Config", "Modifier la config", "Editar configuración", "Konfig bearbeiten");
            E("MW.Panel.RestartCrontab", "Restart Crontab", "Planification de redémarrage", "Reinicio programado", "Neustartplan");
            E("MW.Panel.AutoStart", "Auto Start", "Démarrage auto", "Inicio automático", "Auto-Start");
            E("MW.Panel.EmbedConsole", "Embed Console", "Console intégrée", "Consola integrada", "Konsole einbetten");
            E("MW.Panel.AutoRestart", "Auto Restart", "Redémarrage auto", "Reinicio automático", "Auto-Neustart");
            E("MW.Panel.AutoUpdate", "Auto Update", "Mise à jour auto", "Actualización automática", "Auto-Update");
            E("MW.Panel.UpdateOnStart", "Update on Start", "Mise à jour au démarrage", "Actualizar al iniciar", "Beim Start aktualisieren");
            E("MW.Panel.BackupOnStart", "Backup on Start", "Sauvegarde au démarrage", "Copia al iniciar", "Beim Start sichern");
            E("MW.Panel.DiscordAlert", "Discord Alert", "Alerte Discord", "Alerta de Discord", "Discord-Benachrichtigung");
            E("MW.Panel.SetMessage", "Set Message", "Définir le message", "Definir mensaje", "Nachricht festlegen");
            E("MW.Panel.TestAlert", "Test Alert", "Tester l'alerte", "Probar alerta", "Benachrichtigung testen");
            E("MW.Panel.Settings", "Settings", "Paramètres", "Ajustes", "Einstellungen");
            E("MW.Panel.RamWatchdog", "RAM Watchdog", "Surveillance RAM", "Vigilancia de RAM", "RAM-Überwachung");
            E("MW.Panel.Limit", "Limit", "Limite", "Límite", "Limit");
            E("MW.Panel.BackupBeforeUpdate", "Backup before update", "Sauvegarder avant mise à jour", "Copia antes de actualizar", "Vor Update sichern");
            E("MW.Panel.BackupBeforeUpdateTip", "Back up the server before each update (uses disk space)", "Sauvegarder le serveur avant chaque mise à jour (utilise de l'espace disque)", "Hacer copia del servidor antes de cada actualización (usa espacio en disco)", "Server vor jedem Update sichern (belegt Speicherplatz)");
            E("MW.Panel.Log", "Log:", "Journal :", "Registro:", "Protokoll:");
            E("MW.Console.AutoScroll", "✔ Auto Scroll", "✔ Défilement auto", "✔ Desplazamiento auto", "✔ Auto-Scrollen");
            E("MW.Console.Send", "Send", "Envoyer", "Enviar", "Senden");
            E("MW.Backups.Title", "Backups", "Sauvegardes", "Copias de seguridad", "Sicherungen");
            E("MW.Backups.ServerLabel", "Server:", "Serveur :", "Servidor:", "Server:");
            E("MW.Backups.Refresh", "Refresh", "Actualiser", "Actualizar", "Aktualisieren");
            E("MW.Backups.BackUpAll", "Back up all", "Tout sauvegarder", "Copiar todo", "Alle sichern");
            E("MW.Backups.FolderLabel", "Backup folder:", "Dossier de sauvegarde :", "Carpeta de copias:", "Sicherungsordner:");
            E("MW.Backups.Change", "Change…", "Changer…", "Cambiar…", "Ändern…");
            E("MW.Backups.Folders", "Folders…", "Dossiers…", "Carpetas…", "Ordner…");
            E("MW.Backups.FoldersTip", "Limit the backup to specific subfolders of serverfiles (e.g. savegame). Empty = everything (#179).", "Limiter la sauvegarde à certains sous-dossiers de serverfiles (ex. savegame). Vide = tout (#179).", "Limitar la copia a subcarpetas concretas de serverfiles (p. ej. savegame). Vacío = todo (#179).", "Sicherung auf bestimmte Unterordner von serverfiles beschränken (z. B. savegame). Leer = alles (#179).");
            E("MW.Backups.LocationTip", "Location where this server's backups are stored", "Emplacement où sont stockées les sauvegardes de ce serveur", "Ubicación donde se guardan las copias de este servidor", "Speicherort der Sicherungen dieses Servers");
            E("MW.Backups.Col.Backup", "Backup", "Sauvegarde", "Copia", "Sicherung");
            E("MW.Backups.Col.Date", "Date", "Date", "Fecha", "Datum");
            E("MW.Backups.Col.Size", "Size", "Taille", "Tamaño", "Größe");
            E("MW.Backups.BackUpThis", "Back up this server", "Sauvegarder ce serveur", "Copiar este servidor", "Diesen Server sichern");
            E("MW.Backups.OpenFolder", "Open folder", "Ouvrir le dossier", "Abrir carpeta", "Ordner öffnen");
            E("MW.Backups.AutoBackupAt", "Auto backup at", "Sauvegarde auto à", "Copia automática a las", "Auto-Sicherung um");
            E("MW.Backups.AutoBackupTip", "Daily automatic backup at the chosen time (stop → backup → restart)", "Sauvegarde automatique quotidienne à l'heure choisie (arrêt → sauvegarde → redémarrage)", "Copia automática diaria a la hora elegida (detener → copiar → reiniciar)", "Tägliche automatische Sicherung zur gewählten Uhrzeit (stoppen → sichern → neu starten)");
            E("MW.Nav.ToggleTip", "Collapse / pin the menu", "Réduire / épingler le menu", "Contraer / fijar el menú", "Menü ein-/ausklappen bzw. anheften");
            E("MW.Nav.Home", "Home", "Accueil", "Inicio", "Startseite");
            E("MW.Nav.Dashboard", "Dashboard", "Tableau de bord", "Panel", "Übersicht");
            E("MW.Nav.DiscordBot", "Discord Bot", "Bot Discord", "Bot de Discord", "Discord-Bot");
            E("MW.Nav.Backups", "Backups", "Sauvegardes", "Copias de seguridad", "Sicherungen");
            E("MW.Nav.Plugins", "Plugins", "Plugins", "Plugins", "Plugins");
            E("MW.Nav.Settings", "Settings", "Paramètres", "Ajustes", "Einstellungen");
            E("MW.Nav.Ports", "Ports / UPnP", "Ports / UPnP", "Puertos / UPnP", "Ports / UPnP");
            E("MW.Nav.Doctor", "Server Doctor", "Docteur serveur", "Doctor del servidor", "Server-Doktor");
            E("MW.Nav.Notifications", "Notifications", "Notifications", "Notificaciones", "Benachrichtigungen");
            E("MW.Nav.WebApi", "Web API", "API Web", "API web", "Web-API");

            // ==== MainWindow dialogs (Msg.*) ====
            E("Msg.ErrorTitle", "ERROR", "ERREUR", "ERROR", "FEHLER");
            E("Msg.FailedTitle", "Failed", "Échec", "Error", "Fehlgeschlagen");
            E("Msg.ConfirmationTitle", "Confirmation", "Confirmation", "Confirmación", "Bestätigung");
            E("Msg.InstallingBusy", "WindowsGSM is currently installing/importing server!", "WindowsGSM est en train d'installer/importer un serveur !", "¡WindowsGSM está instalando/importando un servidor en este momento!", "WindowsGSM installiert/importiert gerade einen Server!");
            E("Msg.GenericSteamInstalled", "{0} (AppID {1}) installed.\nExecutable: {2} {3}", "{0} (AppID {1}) installé.\nExécutable : {2} {3}", "{0} (AppID {1}) instalado.\nEjecutable: {2} {3}", "{0} (AppID {1}) installiert.\nAusführbare Datei: {2} {3}");
            E("Msg.ServerAddedTitle", "Server added", "Serveur ajouté", "Servidor añadido", "Server hinzugefügt");
            E("Msg.GenericSteamInstallFailed", "Installation failed (AppID {0}).\n{1}", "Échec de l'installation (AppID {0}).\n{1}", "Error en la instalación (AppID {0}).\n{1}", "Installation fehlgeschlagen (AppID {0}).\n{1}");
            E("Msg.PathNotAccessible", "{0} is not accessible!", "{0} n'est pas accessible !", "¡{0} no es accesible!", "Auf {0} kann nicht zugegriffen werden!");
            E("Msg.ImportCopyFailed", "Fail to copy the directory.\n{0}\nto\n{1}\n\nYou may install a new server and copy the old servers file to the new server.\n\nException: {2}", "Échec de la copie du dossier.\n{0}\nvers\n{1}\n\nTu peux installer un nouveau serveur et copier les fichiers de l'ancien serveur vers le nouveau.\n\nException : {2}", "Error al copiar la carpeta.\n{0}\na\n{1}\n\nPuedes instalar un servidor nuevo y copiar los archivos del servidor antiguo al nuevo.\n\nExcepción: {2}", "Kopieren des Verzeichnisses fehlgeschlagen.\n{0}\nnach\n{1}\n\nDu kannst einen neuen Server installieren und die Dateien des alten Servers auf den neuen kopieren.\n\nAusnahme: {2}");
            E("Msg.DuplicateTitle", "Duplicate", "Dupliquer", "Duplicar", "Duplizieren");
            E("Msg.DuplicateSelectFirst", "Select a server to duplicate first.", "Sélectionne d'abord un serveur à dupliquer.", "Selecciona primero un servidor para duplicar.", "Wähle zuerst einen zu duplizierenden Server aus.");
            E("Msg.DuplicateNoFreeId", "No free ID (max {0}).", "Aucun ID libre (max {0}).", "No hay ID libre (máx. {0}).", "Keine freie ID (max. {0}).");
            E("Msg.DuplicateFailed", "Duplication failed: {0}", "Échec de la duplication : {0}", "Error al duplicar: {0}", "Duplizieren fehlgeschlagen: {0}");
            E("Msg.DeleteServerConfirm", "Do you want to delete this server?\n(There is no comeback)", "Veux-tu supprimer ce serveur ?\n(Aucun retour en arrière possible)", "¿Quieres eliminar este servidor?\n(No hay vuelta atrás)", "Möchtest du diesen Server löschen?\n(Es gibt kein Zurück)");
            E("Msg.SaveButton", "Save", "Enregistrer", "Guardar", "Speichern");
            E("Msg.DiscordWebhookTitle", "Discord Webhook URL", "URL du webhook Discord", "URL del webhook de Discord", "Discord-Webhook-URL");
            E("Msg.DiscordWebhookPrompt", "Please enter the discord webhook url.", "Saisis l'URL du webhook Discord.", "Introduce la URL del webhook de Discord.", "Bitte gib die Discord-Webhook-URL ein.");
            E("Msg.DiscordMessageTitle", "Discord Custom Message", "Message Discord personnalisé", "Mensaje personalizado de Discord", "Benutzerdefinierte Discord-Nachricht");
            E("Msg.DiscordMessagePrompt", "Please enter the custom message.\n\nExample ping message <@discorduserid>:\n<@348921660361146380>", "Saisis le message personnalisé.\n\nExemple de message de mention <@discorduserid> :\n<@348921660361146380>", "Introduce el mensaje personalizado.\n\nEjemplo de mensaje de mención <@discorduserid>:\n<@348921660361146380>", "Bitte gib die benutzerdefinierte Nachricht ein.\n\nBeispiel für eine Erwähnung <@discorduserid>:\n<@348921660361146380>");
            E("Msg.UpdateServerConfirm", "Do you want to update this server?", "Veux-tu mettre à jour ce serveur ?", "¿Quieres actualizar este servidor?", "Möchtest du diesen Server aktualisieren?");
            E("Msg.UpdateAllTitle", "Update all", "Tout mettre à jour", "Actualizar todo", "Alle aktualisieren");
            E("Msg.UpdateAllNone", "No stopped server with an available update.", "Aucun serveur arrêté avec une mise à jour disponible.", "No hay ningún servidor detenido con una actualización disponible.", "Kein gestoppter Server mit verfügbarem Update.");
            E("Msg.UpdateAllConfirm", "Update these {0} server(s)?\n\n{1}", "Mettre à jour ces {0} serveur(s) ?\n\n{1}", "¿Actualizar estos {0} servidor(es)?\n\n{1}", "Diese {0} Server aktualisieren?\n\n{1}");
            E("Msg.BackupAllTitle", "Back up all", "Tout sauvegarder", "Copiar todo", "Alle sichern");
            E("Msg.BackupAllNone", "No stopped server to back up.", "Aucun serveur arrêté à sauvegarder.", "No hay ningún servidor detenido para copiar.", "Kein gestoppter Server zum Sichern.");
            E("Msg.BackupAllConfirm", "Back up these {0} stopped server(s)?", "Sauvegarder ces {0} serveur(s) arrêté(s) ?", "¿Hacer copia de estos {0} servidor(es) detenido(s)?", "Diese {0} gestoppten Server sichern?");
            E("Msg.ValidateServerConfirm", "Do you want to validate this server?", "Veux-tu valider ce serveur ?", "¿Quieres validar este servidor?", "Möchtest du diesen Server validieren?");
            E("Msg.BackupServerConfirm", "Do you want to backup on this server?", "Veux-tu sauvegarder ce serveur ?", "¿Quieres hacer una copia de este servidor?", "Möchtest du diesen Server sichern?");
            E("Msg.TruckPackagesTitle", "server_packages missing", "server_packages manquant", "Falta server_packages", "server_packages fehlt");
            E("Msg.TruckPackagesContent", "This Truck Simulator server has no save\\server_packages.sii + .dat: it will probably crash at startup.\n\nFrom the CLIENT (config.cfg: uset g_console \"1\"), launch the game with ALL your DLC loaded, open the console (~) and type:\n    export_server_packages\nThen restart this server: the plugin copies the files automatically.\n\nStart anyway?", "Ce serveur Truck Simulator n'a pas de save\\server_packages.sii + .dat : il va probablement planter au démarrage.\n\nDepuis le CLIENT (config.cfg : uset g_console \"1\"), lance le jeu avec TOUS tes DLC chargés, ouvre la console (~) et tape :\n    export_server_packages\nRedémarre ensuite ce serveur : le plugin copie les fichiers automatiquement.\n\nDémarrer quand même ?", "Este servidor de Truck Simulator no tiene save\\server_packages.sii + .dat: probablemente fallará al iniciar.\n\nDesde el CLIENTE (config.cfg: uset g_console \"1\"), inicia el juego con TODOS tus DLC cargados, abre la consola (~) y escribe:\n    export_server_packages\nLuego reinicia este servidor: el plugin copia los archivos automáticamente.\n\n¿Iniciar de todos modos?", "Dieser Truck-Simulator-Server hat keine save\\server_packages.sii + .dat: Er stürzt beim Start wahrscheinlich ab.\n\nStarte im CLIENT (config.cfg: uset g_console \"1\") das Spiel mit ALLEN geladenen DLCs, öffne die Konsole (~) und gib ein:\n    export_server_packages\nStarte diesen Server anschließend neu: Das Plugin kopiert die Dateien automatisch.\n\nTrotzdem starten?");
            E("Msg.StartAnywayButton", "Start anyway", "Démarrer quand même", "Iniciar de todos modos", "Trotzdem starten");
            E("Msg.CancelButton", "Cancel", "Annuler", "Cancelar", "Abbrechen");
            E("Msg.ActionHistoryTitle", "Action History", "Historique des actions", "Historial de acciones", "Aktionsverlauf");
            E("Msg.SelectServerFirst", "Select a server first.", "Sélectionne d'abord un serveur.", "Selecciona primero un servidor.", "Wähle zuerst einen Server aus.");
            E("Msg.NoActionRecorded", "No action recorded for this server.", "Aucune action enregistrée pour ce serveur.", "No hay ninguna acción registrada para este servidor.", "Keine Aktion für diesen Server aufgezeichnet.");
            E("Msg.HistoryTitle", "History — #{0} {1}", "Historique — #{0} {1}", "Historial — #{0} {1}", "Verlauf — #{0} {1}");
            E("Msg.UptimeTitle", "Uptime", "Disponibilité", "Tiempo activo", "Betriebszeit");
            E("Msg.UptimeStatsTitle", "Uptime — #{0} {1}", "Disponibilité — #{0} {1}", "Tiempo activo — #{0} {1}", "Betriebszeit — #{0} {1}");
            E("Msg.UptimeBody", "Tracked since: {0}\n\nStarts: {1}\nCrashes: {2}\nTotal online time: {3}\nUptime: {4} %", "Suivi depuis : {0}\n\nDémarrages : {1}\nPlantages : {2}\nTemps en ligne total : {3}\nDisponibilité : {4} %", "Seguimiento desde: {0}\n\nInicios: {1}\nFallos: {2}\nTiempo total en línea: {3}\nDisponibilidad: {4} %", "Erfasst seit: {0}\n\nStarts: {1}\nAbstürze: {2}\nGesamte Online-Zeit: {3}\nVerfügbarkeit: {4} %");
            E("Msg.ActivateButton", "Activate", "Activer", "Activar", "Aktivieren");
            E("Msg.DonorConnectTitle", "Donor Connect (Patreon)", "Connexion donateur (Patreon)", "Conexión de donante (Patreon)", "Spender-Verbindung (Patreon)");
            E("Msg.DonorConnectPrompt", "Please enter the activation key.", "Saisis la clé d'activation.", "Introduce la clave de activación.", "Bitte gib den Aktivierungsschlüssel ein.");
            E("Msg.DonorSuccessTitle", "Success!", "Réussi !", "¡Correcto!", "Erfolg!");
            E("Msg.DonorSuccessBody", "Thanks for your donation {0}, your support help us a lot!\nYou can choose any theme you like on the Settings!", "Merci pour ton don {0}, ton soutien nous aide beaucoup !\nTu peux choisir le thème que tu veux dans les Paramètres !", "¡Gracias por tu donación {0}, tu apoyo nos ayuda mucho!\n¡Puedes elegir el tema que quieras en los Ajustes!", "Danke für deine Spende {0}, deine Unterstützung hilft uns sehr!\nDu kannst in den Einstellungen ein beliebiges Design wählen!");
            E("Msg.DonorFailTitle", "Fail to activate.", "Échec de l'activation.", "Error al activar.", "Aktivierung fehlgeschlagen.");
            E("Msg.DonorFailBody", "Please visit https://windowsgsm.com/patreon/ to get the key.", "Rends-toi sur https://windowsgsm.com/patreon/ pour obtenir la clé.", "Visita https://windowsgsm.com/patreon/ para obtener la clave.", "Besuche https://windowsgsm.com/patreon/, um den Schlüssel zu erhalten.");
            E("Msg.LanguageChanged", "Language changed. Restart WindowsGSM to fully apply it everywhere.", "Langue modifiée. Redémarre WindowsGSM pour l'appliquer partout.", "Idioma cambiado. Reinicia WindowsGSM para aplicarlo por completo en todas partes.", "Sprache geändert. Starte WindowsGSM neu, um sie überall vollständig anzuwenden.");
            E("Msg.SoftwareUpdatesTitle", "Software Updates", "Mises à jour du logiciel", "Actualizaciones de software", "Software-Updates");
            E("Msg.UpdateCheckFailed", "Fail to get latest version, please try again later.", "Impossible de récupérer la dernière version, réessaie plus tard.", "No se pudo obtener la última versión, inténtalo de nuevo más tarde.", "Neueste Version konnte nicht abgerufen werden, bitte versuche es später erneut.");
            E("Msg.UpToDate", "WindowsGSM is up to date.", "WindowsGSM est à jour.", "WindowsGSM está actualizado.", "WindowsGSM ist auf dem neuesten Stand.");
            E("Msg.UpdateButton", "Update", "Mettre à jour", "Actualizar", "Aktualisieren");
            E("Msg.UpdateAvailable", "Version {0} is available, would you like to update now?\n\nWarning: All servers will be shutdown!", "La version {0} est disponible, veux-tu mettre à jour maintenant ?\n\nAttention : tous les serveurs seront arrêtés !", "La versión {0} está disponible, ¿quieres actualizar ahora?\n\nAdvertencia: ¡se detendrán todos los servidores!", "Version {0} ist verfügbar, möchtest du jetzt aktualisieren?\n\nWarnung: Alle Server werden heruntergefahren!");
            E("Msg.UpdaterDownloadFailed", "Fail to download WindowsGSM-Updater.exe", "Échec du téléchargement de WindowsGSM-Updater.exe", "Error al descargar WindowsGSM-Updater.exe", "Download von WindowsGSM-Updater.exe fehlgeschlagen");
            E("Msg.PatreonButton", "Patreon", "Patreon", "Patreon", "Patreon");
            E("Msg.OkButton", "Ok", "Ok", "Ok", "Ok");
            E("Msg.AboutTitle", "About WindowsGSM", "À propos de WindowsGSM", "Acerca de WindowsGSM", "Über WindowsGSM");
            E("Msg.AboutBody", "Product:\t\tWindowsGSM\nVersion:\t\t{0}\nCreator:\t\tTatLead\n\nIf you like WindowsGSM, consider becoming a Patron!", "Produit :\t\tWindowsGSM\nVersion :\t\t{0}\nCréateur :\t\tTatLead\n\nSi tu aimes WindowsGSM, envisage de devenir Patron !", "Producto:\t\tWindowsGSM\nVersión:\t\t{0}\nCreador:\t\tTatLead\n\n¡Si te gusta WindowsGSM, considera hacerte Patron!", "Produkt:\t\tWindowsGSM\nVersion:\t\t{0}\nErsteller:\t\tTatLead\n\nWenn dir WindowsGSM gefällt, werde doch Patron!");
            E("Msg.SelectServerFromList", "Select a server from the list first.", "Sélectionne d'abord un serveur dans la liste.", "Selecciona primero un servidor de la lista.", "Wähle zuerst einen Server aus der Liste aus.");
            E("Msg.ConfigEditorTitle", "Config Editor", "Éditeur de config", "Editor de config", "Konfig-Editor");
            E("Msg.ModsTitle", "Mods", "Mods", "Mods", "Mods");
            E("Msg.ApiTokenTitle", "API Token", "Jeton API", "Token de API", "API-Token");
            E("Msg.GlobalListTitle", "Global Server List Check", "Vérification de la liste globale des serveurs", "Comprobación de la lista global de servidores", "Prüfung der globalen Serverliste");
            E("Msg.GlobalListOnline", "{0}\n\nResult: Online\n\nYour server is on the global server list!", "{0}\n\nRésultat : En ligne\n\nTon serveur est dans la liste globale des serveurs !", "{0}\n\nResultado: En línea\n\n¡Tu servidor está en la lista global de servidores!", "{0}\n\nErgebnis: Online\n\nDein Server steht in der globalen Serverliste!");
            E("Msg.GlobalListOffline", "{0}\n\nResult: Offline\n\nYour server is not on the global server list.", "{0}\n\nRésultat : Hors ligne\n\nTon serveur n'est pas dans la liste globale des serveurs.", "{0}\n\nResultado: Desconectado\n\nTu servidor no está en la lista global de servidores.", "{0}\n\nErgebnis: Offline\n\nDein Server steht nicht in der globalen Serverliste.");
            E("Msg.ToolAmxTitle", "Tools - Install AMX Mod X & MetaMod-P", "Outils - Installer AMX Mod X & MetaMod-P", "Herramientas - Instalar AMX Mod X y MetaMod-P", "Werkzeuge - AMX Mod X & MetaMod-P installieren");
            E("Msg.ToolSourceModTitle", "Tools - Install SourceMod & MetaMod", "Outils - Installer SourceMod & MetaMod", "Herramientas - Instalar SourceMod y MetaMod", "Werkzeuge - SourceMod & MetaMod installieren");
            E("Msg.ToolDayZSALTitle", "Tools - Install DayZSAL Mod Server", "Outils - Installer DayZSAL Mod Server", "Herramientas - Instalar DayZSAL Mod Server", "Werkzeuge - DayZSAL Mod Server installieren");
            E("Msg.ToolOxideTitle", "Tools - Install OxideMod", "Outils - Installer OxideMod", "Herramientas - Instalar OxideMod", "Werkzeuge - OxideMod installieren");
            E("Msg.AddonNotSupported", "Doesn't support on {0} (ID: {1})", "Non pris en charge sur {0} (ID : {1})", "No compatible con {0} (ID: {1})", "Wird auf {0} nicht unterstützt (ID: {1})");
            E("Msg.AddonAlreadyInstalled", "Already Installed (ID: {0})", "Déjà installé (ID : {0})", "Ya instalado (ID: {0})", "Bereits installiert (ID: {0})");
            E("Msg.AddonConfirmInstall", "Are you sure to install? (ID: {0})", "Es-tu sûr de vouloir installer ? (ID : {0})", "¿Seguro que quieres instalar? (ID: {0})", "Wirklich installieren? (ID: {0})");
            E("Msg.AddonConfirmInstallUpdate", "Are you sure to install/Update? (ID: {0})", "Es-tu sûr de vouloir installer/mettre à jour ? (ID : {0})", "¿Seguro que quieres instalar/actualizar? (ID: {0})", "Wirklich installieren/aktualisieren? (ID: {0})");
            E("Msg.AddonInstalledOk", "Installed successfully", "Installé avec succès", "Instalado correctamente", "Erfolgreich installiert");
            E("Msg.AddonInstallFail", "Fail to install", "Échec de l'installation", "Error al instalar", "Installation fehlgeschlagen");
            E("Msg.AddonResult", "{0} (ID: {1})", "{0} (ID : {1})", "{0} (ID: {1})", "{0} (ID: {1})");
            E("Msg.MaintenanceTitle", "Maintenance", "Maintenance", "Mantenimiento", "Wartung");
            E("Msg.MaintenanceEnabled", "Maintenance mode ENABLED for #{0} {1}.\nAuto-start and auto-restart are suspended: the server will not be restarted automatically (ideal for intervening without WGSM restarting it).", "Mode maintenance ACTIVÉ pour #{0} {1}.\nLe démarrage et le redémarrage automatiques sont suspendus : le serveur ne sera pas redémarré automatiquement (idéal pour intervenir sans que WGSM le relance).", "Modo mantenimiento ACTIVADO para #{0} {1}.\nEl inicio y reinicio automáticos están suspendidos: el servidor no se reiniciará automáticamente (ideal para intervenir sin que WGSM lo reinicie).", "Wartungsmodus AKTIVIERT für #{0} {1}.\nAuto-Start und Auto-Neustart sind ausgesetzt: Der Server wird nicht automatisch neu gestartet (ideal, um einzugreifen, ohne dass WGSM ihn neu startet).");
            E("Msg.MaintenanceDisabled", "Maintenance mode disabled for #{0} {1}.", "Mode maintenance désactivé pour #{0} {1}.", "Modo mantenimiento desactivado para #{0} {1}.", "Wartungsmodus deaktiviert für #{0} {1}.");
            E("Msg.DiscordAdminTitle", "Discord Admin", "Admin Discord", "Administrador de Discord", "Discord-Admin");
            E("Msg.SelectAdminFirst", "Select an admin from the list first.", "Sélectionne d'abord un admin dans la liste.", "Selecciona primero un administrador de la lista.", "Wähle zuerst einen Admin aus der Liste aus.");
            E("Msg.InvalidDiscordId", "Invalid Discord ID: it must contain 17 to 20 digits.", "ID Discord invalide : elle doit contenir 17 à 20 chiffres.", "ID de Discord no válido: debe contener de 17 a 20 dígitos.", "Ungültige Discord-ID: Sie muss 17 bis 20 Ziffern enthalten.");
            E("Msg.CheckAtLeastOneServer", "Check at least one server, or \"All servers\".", "Coche au moins un serveur, ou « Tous les serveurs ».", "Marca al menos un servidor, o \"Todos los servidores\".", "Wähle mindestens einen Server oder \"Alle Server\" aus.");
            E("Msg.BackupTitle", "Backup", "Sauvegarde", "Copia de seguridad", "Sicherung");
            E("Msg.MustBeStoppedBackup", "The server must be stopped to back it up.", "Le serveur doit être arrêté pour le sauvegarder.", "El servidor debe estar detenido para hacer la copia.", "Der Server muss gestoppt sein, um ihn zu sichern.");
            E("Msg.RestoreTitle", "Restore", "Restaurer", "Restaurar", "Wiederherstellen");
            E("Msg.MustBeStoppedRestore", "The server must be stopped to restore.", "Le serveur doit être arrêté pour la restauration.", "El servidor debe estar detenido para restaurar.", "Der Server muss gestoppt sein, um wiederherzustellen.");
            E("Msg.RestoreConfirm", "Restore \"{0}\" onto #{1} {2}?\nThe current files will be replaced.", "Restaurer « {0} » sur #{1} {2} ?\nLes fichiers actuels seront remplacés.", "¿Restaurar \"{0}\" en #{1} {2}?\nSe reemplazarán los archivos actuales.", "\"{0}\" auf #{1} {2} wiederherstellen?\nDie aktuellen Dateien werden ersetzt.");
            E("Msg.DeleteTitle", "Delete", "Supprimer", "Eliminar", "Löschen");
            E("Msg.DeleteBackupConfirm", "Permanently delete \"{0}\"?", "Supprimer définitivement « {0} » ?", "¿Eliminar \"{0}\" de forma permanente?", "\"{0}\" endgültig löschen?");
            E("Msg.BackupFoldersTitle", "Folders to back up", "Dossiers à sauvegarder", "Carpetas para la copia", "Zu sichernde Ordner");
            E("Msg.BackupFoldersEverything", "(everything)", "(tout)", "(todo)", "(alles)");
            E("Msg.BackupFoldersPrompt", "Subfolders of serverfiles to include, separated by \"; \". Leave EMPTY to back up everything.\n\nCurrent: {0}\n\nExample (Enshrouded): savegame", "Sous-dossiers de serverfiles à inclure, séparés par « ; ». Laisse VIDE pour tout sauvegarder.\n\nActuel : {0}\n\nExemple (Enshrouded) : savegame", "Subcarpetas de serverfiles a incluir, separadas por \"; \". Deja VACÍO para copiar todo.\n\nActual: {0}\n\nEjemplo (Enshrouded): savegame", "Einzuschließende Unterordner von serverfiles, getrennt durch \"; \". LEER lassen, um alles zu sichern.\n\nAktuell: {0}\n\nBeispiel (Enshrouded): savegame");
            E("Msg.BackupFolderTitle", "Backup folder", "Dossier de sauvegarde", "Carpeta de copias", "Sicherungsordner");
            E("Msg.FolderCreateFailed", "Unable to create/access the folder:\n{0}", "Impossible de créer/d'accéder au dossier :\n{0}", "No se puede crear/acceder a la carpeta:\n{0}", "Ordner kann nicht erstellt werden / kein Zugriff:\n{0}");
            E("Msg.MoveBackupsConfirm", "Move the {0} existing backup(s) to the new folder?", "Déplacer les {0} sauvegarde(s) existante(s) vers le nouveau dossier ?", "¿Mover las {0} copia(s) existente(s) a la nueva carpeta?", "Die {0} vorhandenen Sicherungen in den neuen Ordner verschieben?");

            return all;
        }
    }
}
