using System;
using System.IO;
using System.Linq;
using System.Text;

namespace WindowsGSM.Functions
{
    /// <summary>
    /// Generates a ready-to-compile WindowsGSM game-server plugin (.cs) for a Steam dedicated server
    /// from a small set of parameters (AppID, executable, args, ports…). The template mirrors the proven
    /// plugin shape (SteamCMDAgent base + Plugin metadata + Start/Stop/Update/queries), so the file drops
    /// into plugins\&lt;Name&gt;.cs\&lt;Name&gt;.cs and is compiled by WindowsGSM's Roslyn loader on reload.
    /// </summary>
    public static class PluginGenerator
    {
        /// <summary>Turn a game name into a valid C# class identifier (letters/digits only, not starting with a digit).</summary>
        public static string ToClassName(string gameName)
        {
            var sb = new StringBuilder();
            foreach (char c in (gameName ?? string.Empty))
            {
                if (char.IsLetterOrDigit(c)) { sb.Append(c); }
            }
            string s = sb.ToString();
            if (string.IsNullOrEmpty(s)) { s = "MyGame"; }
            if (char.IsDigit(s[0])) { s = "Game" + s; }
            return s;
        }

        /// <summary>
        /// Generate + write the plugin. Returns (ok, resultPathOrError).
        /// </summary>
        public static (bool ok, string message) Generate(
            string gameName, string author, string appId, string executable, string arguments,
            string port, string queryPort, string maxPlayers, bool useA2S, bool overwrite = false)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(gameName)) { return (false, "Game name is required."); }
                if (string.IsNullOrWhiteSpace(appId) || !appId.All(char.IsDigit)) { return (false, "A numeric Steam AppID is required."); }
                if (string.IsNullOrWhiteSpace(executable)) { return (false, "Executable is required (resolve it from the AppID)."); }

                string className = ToClassName(gameName);
                string dir = Path.Combine(MainWindow.WGSM_PATH, "plugins", className + ".cs");
                string file = Path.Combine(dir, className + ".cs");
                if (File.Exists(file) && !overwrite) { return (false, $"A plugin already exists: {className}.cs (tick overwrite to replace)."); }

                Directory.CreateDirectory(dir);
                File.WriteAllText(file, BuildSource(className, gameName, author, appId, executable, arguments, port, queryPort, maxPlayers, useA2S), new UTF8Encoding(false));
                return (true, file);
            }
            catch (Exception ex)
            {
                return (false, ex.Message);
            }
        }

        private static string BuildSource(string cls, string game, string author, string appId, string exe,
            string args, string port, string queryPort, string maxPlayers, bool useA2S)
        {
            // Escape for a C# string literal (used inside "..."), keep backslashes literal via @"" where used.
            string EscQ(string s) => (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
            string EscV(string s) => (s ?? string.Empty).Replace("\"", "\"\""); // for @"..." verbatim

            string q(string s) => string.IsNullOrWhiteSpace(s) ? "27015" : s.Trim();

            string tpl = TEMPLATE;
            return tpl
                .Replace("__CLASS__", cls)
                .Replace("__GAME__", EscQ(game))
                .Replace("__AUTHOR__", EscQ(string.IsNullOrWhiteSpace(author) ? "Unknown" : author))
                .Replace("__APPID__", appId.Trim())
                .Replace("__EXE__", EscV(exe.Trim()))
                .Replace("__ARGS__", EscV(args ?? string.Empty))
                .Replace("__PORT__", q(port))
                .Replace("__QUERYPORT__", q(queryPort))
                .Replace("__MAX__", string.IsNullOrWhiteSpace(maxPlayers) ? "16" : maxPlayers.Trim())
                .Replace("__QUERY__", useA2S ? "new A2S()" : "null");
        }

        // Token-based template (avoids brace-escaping). __TOKENS__ are replaced above.
        private const string TEMPLATE = @"using System;
using System.IO;
using System.Diagnostics;
using System.Threading.Tasks;
using WindowsGSM.Functions;
using WindowsGSM.GameServer.Engine;
using WindowsGSM.GameServer.Query;

namespace WindowsGSM.Plugins
{
    public class __CLASS__ : SteamCMDAgent
    {
        // Generated by WindowsGSM's plugin creator.
        public Plugin Plugin = new Plugin
        {
            name = ""WindowsGSM.__CLASS__"",
            author = ""__AUTHOR__"",
            description = ""WindowsGSM plugin for __GAME__ Dedicated Server (generated)"",
            version = ""1.0.0"",
            url = """",
            color = ""#34495E""
        };

        public __CLASS__(ServerConfig serverData) : base(serverData) => base.serverData = _serverData = serverData;
        private readonly ServerConfig _serverData;
        public string Error, Notice;

        public override bool loginAnonymous => true;
        public override string AppId => ""__APPID__"";

        public string FullName = ""__GAME__ Dedicated Server"";
        public override string StartPath => @""__EXE__"";
        public bool AllowsEmbedConsole = true;
        public int PortIncrements = 1;
        public object QueryMethod = __QUERY__;

        public string ServerName = ""__GAME__ Server"";
        public string Defaultmap = string.Empty;
        public string Maxplayers = ""__MAX__"";
        public string Port = ""__PORT__"";
        public string QueryPort = ""__QUERYPORT__"";
        public string Additional = @""__ARGS__"";

        public async void CreateServerCFG() { await Task.CompletedTask; }

        public async Task<Process> Start()
        {
            string workingDir = ServerPath.GetServersServerFiles(_serverData.ServerID);
            string exePath = Path.Combine(workingDir, StartPath);
            if (!File.Exists(exePath)) { Error = $""{StartPath} not found ({exePath})""; return null; }

            string param = $""{Additional} {_serverData.ServerParam}"".Trim();
            bool isBatch = StartPath.EndsWith("".bat"", StringComparison.OrdinalIgnoreCase) || StartPath.EndsWith("".cmd"", StringComparison.OrdinalIgnoreCase);
            string fileName = isBatch ? ""cmd.exe"" : exePath;
            string arguments = isBatch ? $""/c \""{exePath}\"" {param}"" : param;

            var p = new Process
            {
                StartInfo =
                {
                    WorkingDirectory = workingDir,
                    FileName = fileName,
                    Arguments = arguments,
                    WindowStyle = ProcessWindowStyle.Minimized,
                    UseShellExecute = false,
                    CreateNoWindow = true
                },
                EnableRaisingEvents = true
            };

            if (AllowsEmbedConsole)
            {
                p.StartInfo.RedirectStandardInput = true;
                p.StartInfo.RedirectStandardOutput = true;
                p.StartInfo.RedirectStandardError = true;
                var console = new ServerConsole(_serverData.ServerID);
                p.OutputDataReceived += console.AddOutput;
                p.ErrorDataReceived += console.AddOutput;
                p.Start();
                p.BeginOutputReadLine();
                p.BeginErrorReadLine();
            }
            else
            {
                p.Start();
            }
            return p;
        }

        public async Task Stop(Process p)
        {
            await Task.Run(() => { try { if (!p.HasExited) { p.CloseMainWindow(); } } catch { } });
            for (int i = 0; i < 15 && !p.HasExited; i++) { await Task.Delay(1000); }
            if (!p.HasExited) { try { p.Kill(); } catch { } }
        }

        public async Task<Process> Update(bool validate = false, string custom = null)
        {
            var (p, error) = await Installer.SteamCMD.UpdateEx(_serverData.ServerID, AppId, validate, custom: custom, loginAnonymous: loginAnonymous);
            Error = error;
            await Task.Run(() => { p.WaitForExit(); });
            return p;
        }

        public bool IsInstallValid() => File.Exists(ServerPath.GetServersServerFiles(_serverData.ServerID, StartPath));

        public bool IsImportValid(string path) => Directory.Exists(path);

        public string GetLocalBuild()
        {
            var steamCMD = new Installer.SteamCMD();
            return steamCMD.GetLocalBuild(_serverData.ServerID, AppId);
        }

        public async Task<string> GetRemoteBuild()
        {
            var steamCMD = new Installer.SteamCMD();
            return await steamCMD.GetRemoteBuild(AppId);
        }
    }
}
";
    }
}
